### ISSUE TITLE
Review html/semantics/forms/the-input-element/range.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#107]
** Test List **

* html/semantics/forms/the-input-element/range.html

** Rationale **

Not suggesting any concrete action yet, but we should review html/semantics/forms/the-input-element/range.html which has subtests failing across all 3 browsers. Either this needs a spec change to reflect current browsers behavior, either we keep the test as it is. @cdumez has mentioned it's pretty simple to implement these changes in WebKit, but it would leave WebKit uninteroperable with the other 2 browser vendors.

cc @domenic and @annevk to check if there is any spec work needed here.

**Comment by foolip** [comment]
@josepharhar can you take a look?

**Comment by nt1m** [comment]
@emilio @jgraham What do you think?

**Comment by josepharhar** [comment]
Thanks for finding this! I am generally in favor of changing the tests/spec to match the browsers when the browsers are all doing the same thing.

The "The default scale factor is 1 even if step attribute is explicitly set to non-integer value, unless min attribute has non-integer value" test was added by @tomoyukilabs here: https://github.com/web-platform-tests/wpt/pull/167
If I'm reading it correctly, the test description suggests that step should be forced to 1 when the min attribute has an integer value. The test does seem to do this by setting min to 5, but I'm not sure what the motivation is. I've never seen any bugs filed about this in chromium. Perhaps we could just remove the test.

The "Skip ASCII whitespace within input" test was added by @nox here: https://github.com/web-platform-tests/wpt/pull/9084
The "123" value is larger than the default maximum of range inputs, so this test could be fixed by just changing the "123" to "50" or something. I've opened a PR to do this here: https://github.com/web-platform-tests/wpt/pull/35519

**Comment by annevk** [comment]
I think the test is slightly incorrect (and browsers appear correct) as I explained in https://github.com/web-platform-tests/wpt/pull/35519#discussion_r953531805. Hope that helps.

**Comment by nt1m** [comment]
> The default scale factor is 1 even if step attribute is explicitly set to non-integer value, unless min attribute has non-integer value

Does anyone have opinions on how to handle this subtest?

**Comment by foolip** [comment]
@nt1m that subtest seems wrong per spec. https://html.spec.whatwg.org/multipage/input.html#dom-input-step says that the `step` IDL attribute simply reflects the content attribute. The test description doesn't really make sense, and I think we should delete this subtest.

**Comment by foolip** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/35914
