### ISSUE TITLE
[charter] implementation requirement

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/interop#122]
Proposal for the charter text requirements:

- The feature is partially implemented in one or multiple browsers.

Should there be an implementation requirement? I added a third criteria. The reasons is that interop group is not here to do prototyping or even be a platform for starting new features even on the standard track. It's about improving the interop state of features which needs care and love to not be a painful point for webdevs. A missing webdev feature across the Web is not necessary an interop issue, it's just an idea which needs work in a standard group/interest group and be refined there. And hopefully if well develop it will never have to go through this group.

**Comment by foolip** [comment]
This is an interesting question. Everything that we have worked on so far has had some level of implementation when we accepted the proposal. Interesting edge cases are Cascade Layers and the new viewport units, which had not shipped in any stable browser at the beginning of 2022, but were in progress.

I think it would be incredibly hard to meet the bar of spec and test quality without any implementation experience, ruling out most "missing feature" cases. However, if someone did present a case where something is well spec'd, has solid tests we can vet, and there's a connection to some web developer pain, I don't see why to rule it out by charter? If we did, I feel like this would be another "case-by-case exceptions" rule.

That being said, there is some value in making explicit that brand new features are not our thing, as opposed to it being implied.

**Comment by foolip** [comment]
@karlcow we didn't put anything around implementation requirements generally in https://github.com/web-platform-tests/interop/pull/115 or https://github.com/web-platform-tests/interop/pull/130, but for implementation efforts we say:

> If a feature is widely implemented, but lacks a high quality specification or tests, an investigation effort may be appropriate.

For a focus area proposal, nothing rules out a feature with no implementation currently. Do you want to see some change here still?

**Comment by karlcow** [comment]
in my mind a feature area which has no implementation or a very early spec is probably not mature yet. 
And there's a stage for this in the WGs process such as the Candidate Recommendation at W3C or RFC in the IETF. This is **exactly the work of a working group** when the spec is being written to maturity at a CR level. Interop effort should not be a substitute for this and we should save resources where the interop effort matters the most, aka reducing the pain where webdevs feel it.

**Comment by jgraham** [comment]
My take is that we don't need to specify this at the charter level because it's a matter of policy. Right now several participants have made it clear that they will reject proposals that aren't on a standards track and with an appropriate degree of stability. We don't need to also put that in the charter itself because it's then going to be enforced by the consensus rule, nad doing so makes it harder to add/subtract requirements in the future. On the other hand I'm very in favour of putting it in any accompanying materials, so that people understand what criteria people are actually applying to proposals.

**Comment by foolip** [comment]
If we add something, I want to be sure it doesn't rule out proposals like Color Spaces and Functions from Interop 2022, where some parts like `color-mix()` still aren't shipping anywhere. There was an implementation behind a flag in Firefox.

I don't know where others will draw the line exactly, but if there are proposals from WHATWG specs that already have tests, but no implementation yet, then I wouldn't rule out those proposals because of it, especially if it's part of a larger proposal and the small addition makes sense. But if others know they'll object to such cases regardless of the details, then I agree it's just as well to write it down.

**Comment by karlcow** [comment]
I can live with what @jgraham said about being in other materials and not in the charter.

**Comment by foolip** [comment]
@karlcow do you want to send a PR for that?

**Comment by foolip** [comment]
Closing this issue as we finished the charter work in https://github.com/web-platform-tests/interop/pull/102 already. If changes to it are needed, we should discuss in new issues.
