### ISSUE TITLE
Typography bucket

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#13]
**Description**
After web fonts were defined, and before variable fonts were invented, the CSS Font specification added powerful tooling for web designers & developers to use to create refined typography. 

`font-feature-settings` is a CSS property that addresses the low-level plumbing for these ability. It has [broad support](https://caniuse.com/?search=font-feature-settings) across almost all browsers. 
However, Authors are encouraged to never use `font-feature-settings`, and instead use `font-variant-*`.
>This [font-feature-settings] property is a low-level feature designed to handle special cases where no other way to enable or access an OpenType font feature exists. Whenever possible, font-variant shorthand property or an associated longhand property, font-variant-ligatures, font-variant-caps, font-variant-east-asian, font-variant-alternates, font-variant-numeric or font-variant-position should be used. 

Authors cannot currently follow this advice, because not all browser have implemented all of the `font-variant-*` properties. This is holding back typography on the web.

Specifically, these two need to be implemented in Chromium:
- [font-variant-alternates](https://caniuse.com/font-variant-alternates)
- [font-variant-position](https://caniuse.com/mdn-css_properties_font-variant-position)

**Specification**
[CSS Fonts Module Level 4](https://www.w3.org/TR/css-fonts-4/#font-rend-desc)

**Tests**
[font-variant-* tests](https://wpt.fyi/results/css/css-fonts?label=master&label=experimental&product=chrome&product=edge&product=firefox&product=webkitgtk&aligned&q=font-variant-)

**Rationale**
State of CSS Survey 2021 reveals requests for typography improvements.

**Comment by jensimmons** [comment]
If we want to add more typography things to this, we could add support for the IC unit. It's a unit important for typesetting CJK scripts. `1ic` is the full width glyph in the element’s font, as represented by the “水”.

**Comment by jensimmons** [comment]
Also, hanging punctuation: 
https://drafts.csswg.org/css-text-3/#hanging-punctuation-property 
https://developer.mozilla.org/en-US/docs/Web/CSS/hanging-punctuation

**Comment by jensimmons** [comment]
Also, Initial Letter
https://drafts.csswg.org/css-inline/#sizing-drop-initials
https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter

**Comment by jensimmons** [comment]
Also, CSS widows & orphans:
https://drafts.csswg.org/css-break-3/#widows-orphans
https://caniuse.com/css-widows-orphans
https://developer.mozilla.org/en-US/docs/Web/CSS/orphans
https://developer.mozilla.org/en-US/docs/Web/CSS/widows

**Comment by jfkthame** [comment]
If you're thinking of improving support (and interop) for text in CJK scripts, can I propose supporting the Segment Break Transformation rules, which have the potential to make CJK authors' lives considerably better:
https://drafts.csswg.org/css-text-3/#line-break-transform

**Comment by jgraham** [comment]
I think it would be useful to decide which are the highest priority areas in this proposal. Including all the specs/properties mentioned seems like it would end up with something that's too broad, and runs the risk of different implementations picking different subsets to prioritise, so not improving the actual interop. Is there data we can use to help narrow the scope to the features with highest impact?

**Comment by jensimmons** [comment]
Tests for [Segment Break Transformation](https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests/text3?label=master&label=experimental&product=chrome&product=edge&product=firefox&product=webkitgtk&aligned&q=segment%20break%20transformation)

**Comment by foolip** [comment]
The Chromium bugs for `font-variant-alternates` and `font-variant-position` are here:
https://bugs.chromium.org/p/chromium/issues/detail?id=716567
https://bugs.chromium.org/p/chromium/issues/detail?id=1212668

@jensimmons regarding the advice to use `font-variant-alternates` and `font-variant-position` instead of `font-feature-settings`, do you know if it's currently possible to use `font-feature-settings` to achieve the desired effect?

If so, I see that [usage of `font-feature-settings`](https://chromestatus.com/metrics/css/timeline/popularity/514) is quite high, and I wonder if some of that is really working around lack of support for font-variant-*. That would be compelling evidence of a need. If someone can suggest things to search for in httparchive, I could give that a try.

**Comment by gsnedders** [comment]
> @jensimmons regarding the advice to use `font-variant-alternates` and `font-variant-position` instead of `font-feature-settings`, do you know if it's currently possible to use `font-feature-settings` to achieve the desired effect?

it is

**Comment by jensimmons** [comment]
I like to withdraw the suggestion of widows & orphans. While this functionality is highly requested, I don't believe that the current spec solves the problem we designers & developers have. 

Instead, I believe font-size-adjust and/or text-size-adjust would be a better addition to this bucket.

**Comment by jensimmons** [comment]
@foolip `font-feature -*` properties do accomplish the same end-results as `font-variant-*` properties, but Authors are not supposed to be using `font-feature-*`. That's a low level API which is hard to deal with in the cascade, and has a lot of obscure values. The CSSWG intended for Authors to write code using `font-variant-*` exclusively. However, Authors cannot do so, because of the lack of implementations. Which is holding the whole industry back. 

`font-feature -*` is implemented, but is practically impossible to use.

`font-variant -*` is what people should use, but it's not implemented in enough browsers. 

Interop 2022 can help with this. Let's finish these features & make Fonts 4 complete.

**Comment by jensimmons** [comment]
I'm hearing desire for Color Fonts as well: https://drafts.csswg.org/css-fonts-4/#color-font-support

**Comment by jgraham** [comment]
So, can we clarify what the actual proposal here is? It's difficult to understand what people think forms part of the final state of this proposal, and if we don't know that it's not possible to take a stance on it (or at least not a positive stance).

**Comment by gsnedders** [comment]
So, concretely, I believe our proposal is:

### General Typography

1. Support `font-variant` shorthand + longhands
   * [Spec](https://www.w3.org/TR/css-fonts-4/#font-rend-props)
   * [Tests](https://wpt.fyi/results/css/css-fonts?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=font-variant)
2. Support `initial-letter`
   * [Spec](https://www.w3.org/TR/css-inline/#sizing-drop-initials)
   * Needs tests in WPT. (There's some token coverage, and both WebKit and Gecko have some tests in their respective repos.)
3. Support `font-palette` and `@font-palette-values`
    * [Spec](https://www.w3.org/TR/css-fonts-4/#color-font-support)
    * [Tests](https://wpt.fyi/results/css/css-fonts?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=font-palette)

### CJK Typography

Splitting this out, mostly for the sake of clarity; this being split out shouldn't be taken as any suggestion that these should be in any way lower priority.

4. Support the `ic` unit
   * [Spec](https://www.w3.org/TR/css-values-4/#font-relative-lengths)
   * [Tests](https://wpt.fyi/results/css/css-values?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=ic-unit)
5. Support `hanging-punctuation`
   * [Spec](https://www.w3.org/TR/css-text-3/#hanging)
   * [Tests](https://wpt.fyi/results/css/css-text?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=hanging-punctuation), though note there are more tests that are currently missing from automation due to the `font` flag making them get treated as manual tests, due to https://github.com/web-platform-tests/wpt/issues/13203.

**Comment by jensimmons** [comment]
Also under CJK Typography, as suggested by Mozilla:

6. Support `Segment Break Transformation`
- [Spec](https://drafts.csswg.org/css-text-3/#line-break-transform)
- [Tests](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=segment-break-transformation%20or%20seg-break-transformation)

**Comment by achristensen07** [comment]
Along with CJK Typography, it's probably worth including CJK text encoding, particularly iso-2022-jp, gbk, and gb18030

**Comment by foolip** [comment]
Tests for those encodings are here:
https://wpt.fyi/results/encoding/legacy-mb-japanese/iso-2022-jp
https://wpt.fyi/results/encoding/legacy-mb-schinese/gbk
https://wpt.fyi/results/encoding/legacy-mb-schinese/gb18030

**Comment by foolip** [comment]
> 2. Support `initial-letter`
>    
>    * [Spec](https://www.w3.org/TR/css-inline/#sizing-drop-initials)
>    * Needs tests in WPT. (There's some token coverage, and both WebKit and Gecko have some tests in their respective repos.)

I found https://github.com/WebKit/WebKit/tree/main/LayoutTests/fast/css-generated-content but I can't find any tests in Gecko (or Chromium) beyond what's imported from WPT.

How comprehensive are the WebKit tests, and do they match the current spec?

**Comment by foolip** [comment]
For Segment Break Transformation Rules, [the spec](https://drafts.csswg.org/css-text-3/#line-break-transform) has UA-defined behavior:
> Then any remaining segment break is either transformed into a space (U+0020) or removed depending on the context before and after the break. The rules for this operation are UA-defined in this level.

I only looked into this feature today so my misunderstanding is only surface deep, but doesn't this make most of the interesting cases UA-defined? A bunch of the tests were marked tentative in https://github.com/web-platform-tests/wpt/pull/26588 due to https://github.com/w3c/csswg-drafts/issues/5086, which is still open.

**Comment by jfkthame** [comment]
> For Segment Break Transformation Rules, [the spec](https://drafts.csswg.org/css-text-3/#line-break-transform) has UA-defined behavior:
> 
> > Then any remaining segment break is either transformed into a space (U+0020) or removed depending on the context before and after the break. The rules for this operation are UA-defined in this level.
> 
> I only looked into this feature today so my misunderstanding is surface deep, but doesn't this make most of the interesting cases UA-defined? A bunch of the tests were marked tentative in [web-platform-tests/wpt#26588](https://github.com/web-platform-tests/wpt/pull/26588) due to [w3c/csswg-drafts#5086](https://github.com/w3c/csswg-drafts/issues/5086), which is still open.

Yeah, that's unfortunate.... there used to be quite a bit more in the spec, but then details were deferred to Text-4 following the discussion in https://github.com/w3c/csswg-drafts/issues/5086#issuecomment-709398160.

So I guess we'd need to push that spec work forward if any real progress is going to happen here.

(FWIW, I think Gecko implemented something close to what used to be in the Text-3 draft up until a year ago, though there may have been some edge cases where it didn't entirely conform.)

**Comment by foolip** [comment]
I see. https://github.com/w3c/csswg-drafts/commit/b3bb0ed18b3168981c54c437bcfb5881ef49975b seems to be the commit that commented out the rules around this.

**Comment by foolip** [comment]
@gsnedders said on the Matrix channel:

> https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=legacy-mb%20or%20iso-2022-jp-%20or%20ic-unit%20or%20font-variant is in principle vaguely what we want for what the typography issue became, but also calling that all "typography" seems a bit questionable.

I agree. Does anyone have suggestions for another name for this bucket? Or could it make sense to slot encodings under the webcompat bucket, if it has caused any broken sites? @achristensen07 WDYT?

**Comment by karlcow** [comment]
What about "Font Parametrization bucket"?

**Comment by foolip** [comment]
@karlcow https://encoding.spec.whatwg.org/ doesn't really fit well under that banner either. But @annevk suggested just "text" which I think would work.

**Comment by gsnedders** [comment]
I've labelled them as `interop-2022-text` based on @annevk's suggestion, but I'm by no means wedded to that name.

**Comment by foolip** [comment]
Thanks @gsnedders! It would be great if someone from each browser engine team can look over [`interop-2022-text`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-text) and comment if there are any issues.

**Comment by jfkthame** [comment]
The `font-variant` descriptor (as distinct from the `font-variant` property) was dropped from CSS Fonts (as noted at https://drafts.csswg.org/css-fonts-4/#changes-2018-09-20), which means a few of the tests currently listed are not valid. At first glance, this affects font-variant-05.xht, font-variant-06.xht, and font-variant-descriptor-01.html.

**Comment by gsnedders** [comment]
From the discussion earlier, @foolip was going to remove many of the tests in `encoding`, given most already pass. I'd added everything that followed from "including CJK text encoding", not limiting it to the parts particularly mentioned.

[These](https://wpt.fyi/results/encoding?label=master&label=stable&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-text%20count%3A%3C3%28status%3Apass%7Cstatus%3Aok%29) are the tests which don't pass everywhere, which is 8 tests rather than 1209 tests. However, even among those 8 many of those are any.js tests, and it's unclear there's any value to running those in different environments. Do we just want to go down to [these](https://wpt.fyi/results/encoding?label=master&label=stable&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-text%20count%3A%3C3%28status%3Apass%7Cstatus%3Aok%29%20%21any.worker.html) five tests?

**Comment by gsnedders** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/2388 does duly remove the vast majority of the tests (down to six, keeping decode & encode tests for each of three encodings, despite gb18030 encode being interop already).

**Comment by jensimmons** [comment]
For reference, this is what we debated and decided.

Technology Considered | Decision
-- | -- 
font-variant-alternates + font-variant-position | Include
IC unit (CJK focused) | Include
hanging punctuation (JP focused) | Exclude
Initial Letter | Exclude
Color fonts | Exclude
Segment Break Transformation rules | Exclude
CJK text encoding | Include
