### ISSUE TITLE
[JS API] Temporal

### ISSUE THREAD

**Issue by legowerewolf** [web-platform-tests/interop#169]
### Description

Temporal seeks to solve problems with the existing JS Date APIs, namely: 

> 1. No support for time zones other than the user’s local time and UTC
> 2. Parser behavior so unreliable it is unusable
> 3. Date object is mutable
> 4. DST behavior is unpredictable
> 5. Computation APIs are unwieldy
> 6. No support for non-Gregorian calendars

https://maggiepint.com/2017/04/09/fixing-javascript-date-getting-started/

### Rationale

The proliferation of date-and-time handling libraries should be sufficient evidence that the current state of built-in datetime handling APIs is not up to snuff.

### Specification

https://github.com/tc39/proposal-temporal

### Tests

https://test262.report/browse/built-ins/Temporal (thanks @foolip)

**Comment by foolip** [comment]
Looks like there are tests for this here:
https://test262.report/browse/built-ins/Temporal

Looking at https://github.com/tc39/test262/commits/main/test/built-ins/Temporal, it looks like the test are mostly written by @Ms2ger @ptomato @FrankYFTang @jugglinmike. Perhaps they have feedback on whether this test suite is ready, and if the spec for Temporal is ready (enough).

**Comment by Ms2ger** [comment]
Initial implementations are ongoing and still turning up spec issues. I believe we're still aiming for stage 4 by the end of the year, and we're building up the test suite. I'm not sure if it would be useful to include in interop23, but it seems plausible that spec and tests will be in reasonable shape by next year.

**Comment by foolip** [comment]
@Ms2ger would you advise against using it, or are you not sure, as you say?

**Comment by Ms2ger** [comment]
I have no strong feelings one way or the other

**Comment by syg** [comment]
> I believe we're still aiming for stage 4 by the end of the year

Stage 4 for Temporal by EOY 2022 isn't possible, do you mean EOY 2023?

**Comment by foolip** [comment]
Regarding the spec maturity, in the [proposal template](https://github.com/web-platform-tests/interop/blob/main/.github/ISSUE_TEMPLATE/focus-area-proposal.yml) we only ask for Stage 2+ for TC39, and Temporal is currently Stage 3. Of course that doesn't by itself mean that implementers feel it's ready to ship in 2023, we'll use the proposal selection process to determine by consensus what to include and not.

**Comment by tbondwilkinson** [comment]
Temporal is a P1 interop project for Google's [closure library](https://github.com/google/closure-library).

"Provides a path off of goog.date and Date, which are problematic APIs for numerous reasons (primarily mutability and lack of features)."

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Temporal API" was selected by ~18% of survey takers, putting it in the middle third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

**Comment by FrankYFTang** [comment]
I don't think we need to discuss the desire and the importance of Temporal. Everyone agree with that. The reason we are shine from committe to it for 2023 is we so far not yet observe **a trend of stability of the spec text changes** for the proposal text. 

I am the sole SWE on v8 to implementing the code. Syg and AdamK both spent tremendous amount of time and efforts to code review my work and they are great.
See all my work and their efforts on code review the v8 changes
https://chromium-review.googlesource.com/q/owner:ftang%2540chromium.org+Temporal+is:merged

Temporal champions are also working very hard to address the issues we discovered and resolve the issues in their repo. See
https://github.com/tc39/proposal-temporal/issues?page=1&q=is%3Aissue+author%3AFrankYFTang 

But the spec text is just yet too unstable (and incomplete - for example, see what I am going to raise in TC39 next week https://docs.google.com/presentation/d/1hoQUYL_mfdLXMHRsNcG27aJirukuDGsVbqntd_tcR0A/edit#slide=id.g18ff2c138a1_0_32 ) to committe a date to ship.

Take a look at the git log in and that may help you to understand. 
https://github.com/tc39/proposal-temporal/commits/main

I did some simple statistics of the git log and hope that will show you how unstable the spec text still is .

1. if we look at the changes of spec (all the changes inside the spec directory) since the first 2022 commit (excluding any changes outside that directory in polyphil or user documentation). 3a01f000295206d08628093d165c1b3560f002fa

The spec text deleted 3789 lines and added 4913 lines
2. here are some stats of the commit on git each month in 2022
Jan 2022 - 31 commits
Feb 2022 - 43 commits
Mar 2022 - 77 commits
Apr 2022 - 54 commits
May 2022 - 100 commits
Jun 2022 - 149 commits
Jul 2022 - 21 commits
Aug 2022 - 50 commits
Sep 2022 - 30 commits
Oct 2022 - 39 commits
Nov 2022 - 9 commits

Of course, some of their commits are commit to user documentation and polifil and not all to the spec text. but many are. 

Therefore, until the Temporal champions are able to commit to stablize the change to the spec text of Temporal, from my point of view, it is far too early to committe to ship. For example, the Temporal text recently have to make a massive grammar change for a request from IETF. that invalide some of our parser implementation and need some efforts to change our parser to implement that change. (see https://github.com/tc39/proposal-temporal/commit/c64b8447d66b5f7985fbc5b9e49723eeeed7790d ) . How many more changes will come to the spec text? That is the key question. 
We do not know
We know in the last 12 months there are a lot, much much  much much more than what had happened to all the Stage 3 proposals we have work with.  Mostly because this proposal is very very very thick. 
We have no evidence to let us believe the amount of changes will be reduced. All the "believe" of that will happen is based on "faith", "hope", "intend" and "guess" but not based on empirical evidences.  While we also belive the "intend" of the Temporal champion is to reduce the scale of the spec text changes in the near future, there are no evidence to support that they are able to do so, at least not in the amount we hope to see. We hope that will happen, but we do not have the evidence to support us to commit to ship it by the end of 2023 based on all what we observed so far. I may change my opinion 6 months later, if I start to see some trend and tighter change control on that proposal. But so far I have not observe that. Therefore, from our point of view, that is still a moving target to shoot at. A very fast moving moving target, not a slow one.

Therefore, all the information or argument about the demand and desire will have no impact to our committement. We are fully commit to implement all the necessary changes and ship it ASAP already, but the spec text itself is not yet committed to stay frozen. Therefore, it is just simply an impossible task  to ship it so far. The so-called ASAP to ship date may happen in Q3  or Q4 2023, but my confidence is just very low because there are too many factors are out of our hand but in the hand of the Temporal champion and all evidence indicate the spec text is still very volatile as today.

**Comment by nairnandu** [comment]
Thank you for proposing Temporal for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. The specification is still evolving, and integrating the test suite into WPT would be a significant undertaking. This should not be taken as a comment on the technology as a whole, and resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
