### ISSUE TITLE
ES Module support for Web Workers

### ISSUE THREAD

**Issue by potch** [web-platform-tests/interop#192]
### Description

With robust, native ES module support in both the server and the main thread of modern browsers, it would be wonderful to have full support for ES Modules in Web Worker contexts without need for compilation.

### Rationale

* Ease of code reuse
* Syntax isomorphism between main thread and workers will make it easier for devs to pull work off the main thread and increase page responsiveness
* We're so close! ([Firefox is missing support](https://developer.mozilla.org/en-US/docs/Web/API/Worker#browser_compatibility))
  * https://bugzilla.mozilla.org/show_bug.cgi?id=1247687

### Specification

https://html.spec.whatwg.org/multipage/workers.html#module-worker-example

### Tests

https://wpt.fyi/results/workers/modules

**Comment by bkardell** [comment]
The current status quo is very complicated to deal with and I think a lot of people just don't even bother because of it.  This is a thing we kind of need interop on to really realize the potential of and I think that a lot of stuff that uses workers is stuff that people use kind of a lot or have strict perf goals/limits... There are less of them and they are more centralized, so another bit of rationale here is that it is a win for more users requiring less people (who are already acutely aware) to act.

**Comment by tbondwilkinson** [comment]
ES module support for Web Worker is a P3 for Google's [closure library](https://github.com/google/closure-library)

"I don't have a good sense of how widespread the use of workers is, nor the effect it has on the code, but my understanding is that you have to write code differently depending on where it's targetted, and this is a burden on users."

**Comment by foolip** [comment]
Thank you for proposing ES Module support for Web Workers for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Modules focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
