### ISSUE TITLE
MathML Core 

### ISSUE THREAD

**Issue by bkardell** [web-platform-tests/interop#197]
### Description

(split from #147)

This focus-area would aim for improving test scores/support for MathML-Core Level 1 in all browsers.

MathML-Core is, itself, a specification about interoperability and providing a platform integrated definition (subset) of MathML to be supported by browsers.  This focus area would specifically target the remaining integration gaps (some CSS integrations, for example) for Level 1.

### Rationale

Despite its origins, the web has not prioritized the needs of integrating mathematical text into the platform.  The situation has been complex for a long time. All browsers supported the integrations done with the HTML parser, and we had 2 implementations (WebKit and Gecko) with very rough edges, strange oddities and some guesswork where things were unclear.  MathML-Core provides stricter definition, clarifies  and explains platform integration (IDL/CSS, etc).  There is an intent to ship in Chromium currently scheduled for release 109 and have been numerous PRs and work in other engines to align.   Without good support, authors are left to rely on significantly large JavaScript libraries in order to render mathematical text, or use images.  Neither is a solution that we would encourage for any other kind of text, and both disconnect from all of the other text, layout, scripting, accessibility and other integrations of the platform.

While many users will not encounter them in the 'waft and weft' of daily web use, support for it is critical and important.  Students online need good math support.  Our ability to share so many things is affected - there are millions of math equations in Wikipedia alone.  

It is currently the 4th most starred Blink issue (up from 5th not long ago), see [https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component:Blink&sort=-stars&colspec=ID%20Stars%20Pri%20Status%20Component%20Opened%20Summary](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component%3ABlink&sort=-stars&colspec=ID+Stars+Pri+Status+Component+Opened+Summary). 

It would be ideal to make sure that in 2023 we focus on making this very highly interoperable.

### Specification

W3C https://w3c.github.io/mathml-core/
Also a few bits in WHATWG https://html.spec.whatwg.org/
and https://www.w3.org/TR/css-fonts-4/

### Tests

https://wpt.fyi/results/mathml?label=master&label=experimental&aligned&view=subtest&q=mathml
(note that at least a small number of these tests are testing things that were dropped from L1)

**Comment by NSoiffer** [comment]
## Specific ask
To bridge the gap between full MathML and MathML Core, I have written a number of "polyfills". These polyfills assume MathML Core support exists in the browsers. Additionally, the MathML full spec (which we hope to advance to CR late next year), assumes MathML core is implemented in the browsers in which people read the spec. The spec uses the polyfills to illustrate the element.

One feature the transforms assume is that CSS support on MathML elements exists. However, Firefox and Safari are both missing that support.

The polyfill support for `menclose` heavily relies on CSS ([example page](https://mathml-refresh.github.io/mathml-polyfills/acid-test.html#mencloseHeader)). 


### Chrome
In Chrome, before clicking "apply transform", it looks like:
![image](https://user-images.githubusercontent.com/1545836/199108850-8bad03c4-927c-4480-af39-4b9f47d54d12.png)

After clicking, it looks like:
![image(1)](https://user-images.githubusercontent.com/1545836/199108871-821a3b1e-dc7a-4e5e-a873-3662e951ca56.png)


### Firefox and Safari
Firefox and Safari implement a lot, but not all, of the MathML full menclose options. The polyfill tests for a number of features before running, so the before version doesn't look too bad. However, arrows (the second row) are not implemented. So in Firefox (Safari is similar), after clicking on "Apply Transform", you see:
![image(3)](https://user-images.githubusercontent.com/1545836/199109444-c38e3a59-0e54-4a00-8d72-8263b8e608ea.png)

Notice the lack of arrows in the second row. 

### Specifics
The CSS used for menclose can be found at the start of the [menclose JS file](https://github.com/mathml-refresh/mathml-polyfills/blob/main/menclose/menclose.css).

Elementary math also makes use of CSS. The CSS needed for that is at the start of [the elementary math JS file](https://github.com/mathml-refresh/mathml-polyfills/blob/main/elem-math/elemMath.js).

There are some [wpt tests for MathML CSS](https://wpt.fyi/results/mathml/relations/css-styling?label=experimental&label=master&aligned), but they don't cover all the uses found in the polyfills.

**Comment by fred-wang** [comment]
The original report only mentions MathML tests, but we should really also include related CSS tests. The MathML Core spec actually uses a [different link](https://wpt.fyi/results/?label=experimental&label=master&aligned&q=math%20%20not%28path%3A%2Fjs%29). The `html` folder contains the majority of the test (~21400) but most of them are just testing HTML entity names, so they are a bit overrepresented. Let's deal with them first:

- `html/canvas/offscreen` contains 2 (crash) tests failing in WebKit for `font-family: math` in canvas.
- `html/syntax/speculative-parsing/generated` contains 4 tests failing in WebKit/Chromium corresponding to speculative parsing of `<math><script src=...` and `<math><font>...`.
- `html/the-xhtml-syntax/parsing-xhtml-documents` contains 27 tests failing in WebKit corresponding to entity names `&AMP;`, `&LT;` and `&nvlt;` in XHTML documents.

I believe none of the failures above are critical for MathML users. I will need to check the speculative tests in Chromium/WebKit to understand more precisely what's happening. The canvas test in WebKit is probably only failing because of missing `OffScreenCanvas` support. And for the entity names in WebKit, I'm backporting a patch from Chromium here: https://github.com/WebKit/WebKit/pull/6079

So I think for this issue we can focus on [CSS and MathML tests](https://wpt.fyi/results/?label=master&label=experimental&aligned&view=subtest&q=math%20%20not%28path%3A%2Fjs%29%20not%28path%3A%2Fhtml%29). Currently, I'm getting this score:

- Chromium: 92.62%
- Firefox: 73.76%
- WebKit: 69.54%

I'll try to give a more detailed analysis later.

**Comment by bkardell** [comment]
The href-* (3) and tabindex-*.html (64) ones should not be part of this as they are not part of Level 1. Likewise the css/css-text (19) mathvariant-*.html (22) as well - but the rest of this is the list I was suggesting that focus on MathML-Core L1.

**Comment by nairnandu** [comment]
Thank you for proposing Math ML Core for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. This should not be taken as a comment on the technology as a whole, and resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
