### ISSUE TITLE
PWA manifest and push notifications

### ISSUE THREAD

**Issue by ygupta81** [web-platform-tests/interop#218]
### Description

Today there are a few incompatibilities which make working of PWAs (Progressive Web Apps) difficult across browsers 

Web app manifests - https://web.dev/add-manifest/  

This a JSON file that tells the browser about your Progressive Web App and how it should behave when installed on the user's desktop or mobile device. There are a lot of incompatibilities across browsers even for “standard” web app manifest fields like scope, start_url and display. More details can be seen here - https://developer.mozilla.org/en-US/docs/Web/Manifest#browser_compatibility  

Push notifications - https://web.dev/notifications/  

This allows service to push messages to browser even when website is not opened. Push API, Notification API: requestPermission and  ServiceWorkerRegistration API: showNotification  today are not supported by iOS Safari. More details at below links:- 

https://caniuse.com/?search=push%20api  

https://caniuse.com/mdn-api_notification_requestpermission  

https://caniuse.com/mdn-api_serviceworkerregistration_shownotification  

### Rationale

These incompatibilities make life of web developers difficult with respect to following:- 

1. Implementing features like Add to Home Screen with PWAs cannot be done in a consistent way 
3. Implementing push notifications via service worker is not possible in iOS Safari today 

### Specification

- https://w3c.github.io/manifest/  
- https://www.w3.org/TR/push-api/  
- https://notifications.spec.whatwg.org/#dom-notification-requestpermission  
- https://notifications.spec.whatwg.org/#dom-serviceworkerregistration-shownotification  

### Tests

https://wpt.fyi/results/push-api?label=stable&label=master&aligned&view=subtest

**Comment by gsnedders** [comment]
> This a JSON file that tells the browser about your Progressive Web App and how it should behave when installed on the user's desktop or mobile device. There are a lot of incompatibilities across browsers even for “standard” web app manifest fields like scope, start_url and display. More details can be seen here - https://developer.mozilla.org/en-US/docs/Web/Manifest#browser_compatibility

To look at those fields:

* `scope` has green ticks or unknown,
* `start_url` again has green ticks or unknown,
* `display` has green ticks or unknown except for Safari on iOS which is partial and "does not support fullscreen or minimal-ui" (which is debatably true: I believe Safari on iOS correctly implements https://w3c.github.io/manifest/#choosing-a-display-mode, even though it doesn't have distinct UI for all of them).

It's also not clear if any of these can be tested in an automated manner due to many UAs only implementing this on mobile (and WPT not having mobile testing) as well as difficulties in testing what often requires browser UI interaction.

> This allows service to push messages to browser even when website is not opened. Push API, Notification API: requestPermission and ServiceWorkerRegistration API: showNotification today are not supported by iOS Safari.

This similarly

**Comment by gsnedders** [comment]
(not sure how I managed to hit the "close with comment" button there, but apparently I did)

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Push notifications" was selected by ~26% of survey takers, putting it in the top third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

**Comment by nairnandu** [comment]
Thank you for proposing PWA manifest and push notifications for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. 

Some aspects of this technology are expected to work differently between implementations (e.g. due to differing OS conventions). As a result, for the technology that is intended to be interoperable, we are unable to automate tests using the current web-platform-tests infrastructure. For example, we have no means for testing push notifications.

We welcome proposals for future years, although as general advice we suggest scoping any future proposals more narrowly, as smaller, clearly scoped proposals are easier to assess and prioritize.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
