### ISSUE TITLE
Remove nonstandard event.path

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#26]
**Description**
Blink is shipping the nonstandard `event.path` property which was replaced by the `event.composedPath()` method. Sites depending on the nonstandard property has caused significant breakage.

**Bug reports**
https://bugzilla.mozilla.org/show_bug.cgi?id=1697551
https://bugzilla.mozilla.org/show_bug.cgi?id=1697590

**Specification**
[`composedPath`](https://dom.spec.whatwg.org/#dom-event-composedpath)

**Tests**
https://wpt.fyi/results/dom/historical.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned

This is a bug to include in #9

**Comment by foolip** [comment]
It looks like there was no Chromium issue for this, so I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1277431.

@jgraham the test also covers other things, would it be OK to create a new test for just this?

**Comment by jgraham** [comment]
Yeah, we can create a new test, although I really think we should find a way to make the metrics generation work with subtests.

**Comment by foolip** [comment]
It would be straightforward enough to support labeling subtests (like for bug links) but I think there will be very few cases like this. Metric computation is already rather involved, so simplicity is nice to have where it can be had. We'll see when we go write the new code that uses labels instead of the test lists.
