### ISSUE TITLE
Push interop score to >90 by EOY

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#272]
For Interop 2022 it was significant achievement to surpass 90 for all of the top-level scores. However, we didn't set such a goal as a group or track it throughout the year. To do so would have meant each browser engine team reporting on their progress to the others, which would have just been an FYI, not something to act on.

In https://wpt.fyi/interop-2023 we've added an interop score, which starts out at 62. Should we set a goal of getting this above 90 by the end of the year?

Doing this would probably take roughly this shape:
- Sort focus areas by their interop score ([example](https://docs.google.com/spreadsheets/d/1ZQZds4yeBkTntMPvAmaklKRUnnZ5KUnwA_pef1eP2YE/edit#gid=0&fvid=333655408))
- Identify which browser bugs would move the score by most. For example, for Subgrid that would be https://crbug.com/618969 and for `:has()` it would be https://bugzil.la/418039.
- Get an estimate of when bugs will be fixed based on public information
- If we don't know enough to have confidence we'll get to 90 by EOY, ask if there can be an update on the bug. In case we still don't know, just leave it as an unknown and move on to the next biggest item.

**Comment by jensimmons** [comment]
Why would we want to set such an external group goal? Such goals may make sense for companies with OKRs or other cultural reasons to want such a line in the sand, but how about as an internal goal (for your browser score or your contribution to the Interop score). But I don't know that this makes sense for all companies to do. We each have very different cultures, timing, and ways of setting priorities. 

I also don't understand what the benefit is. Clearly the whole project is about raising this number. Why do we need an artificial cutoff that we demand we reach? 

Are you thinking this would translate into putting specific pressure on certain browsers "come on Chrome, you are the reason the Interop score isn't reaching 90%!" Do you believe such pressure would change whether or not a browser team could prioritize engineering work to increase their score? Perhaps at Google it would? 

What happens when we reach 87%? Should Interop 2023 be considered a failure then? What a terrible message. 

I do not see how this is needed. Or helpful.

We came together to choose focus areas and tests. I believe we should leave it up to each team to figure out how best to contribute. Not create additional pressure to reach an artificial number.

**Comment by foolip** [comment]
We discussed this in https://github.com/web-platform-tests/interop/issues/278 and the takeaway is that there's no appetite for coordination to improve this metric directly.

I will continue to update [this spreadsheet](https://docs.google.com/spreadsheets/d/1ZQZds4yeBkTntMPvAmaklKRUnnZ5KUnwA_pef1eP2YE/edit#gid=507379792&fvid=129488210) and consider both Chrome's score and the Interop score when Chrome teams ask for advice on what to prioritize first.
