### ISSUE TITLE
HTMLElement.onbeforeinput

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#28]
**Description**
Gecko and WebKit implement HTMLElement.onbeforeinput as an event handler attribute for the beforeInput event, but this is missing in Blink. This allows feature detection of the beforeInput event.

**Bug reports**
[CHR-947408](https://bugs.chromium.org/p/chromium/issues/detail?id=947408)

**Specification**
https://github.com/w3c/uievents/issues/218

**Tests**
Need to write a test

This is a bug to include in #9

**Comment by foolip** [comment]
Both spec and test are missing here, but are trivial since this is about the `onbeforeinput` event handler attribute only.

**Comment by foolip** [comment]
Open spec PR in https://github.com/whatwg/html/pull/6743. If added to IDL, it would flow into WPT and end up in idlharness.js tests.

However, we couldn't really use HTML's idlharness.js test for Interop 2022, since they test all of HTML's IDL, and so far we've only tracked tests, not subtests. Adding a single test for the attribute is probably best.
