### ISSUE TITLE
Review Interop 2022 dashboard changes

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#283]
https://wpt.fyi/interop-2022 is now using the same style as Interop 2023. We have talked about making some changes retroactively to the Interop 2022 dashboard, but I don't think we made an explicit decision. The points in particular:

- The INTEROP and INVESTIGATIONS circles on top weren't there originally
- Interop 2022 had a 10%/90% mix of investigation efforts and focus area scores

Note that https://wpt.fyi/interop-2021 doesn't have the top two circles, but it does have the interop column.

This relates to if/how/when we should archive the dashboards of past efforts.

**Comment by foolip** [comment]
cc @DanielRyanSmith

**Comment by foolip** [comment]
@DanielRyanSmith do you know if there's some way to see the Interop 2022 dashboard as it was before the recent changes? https://web.archive.org/web/20230101023900/https://wpt.fyi/interop-2022 is just a blank page.

**Comment by DanielRyanSmith** [comment]
I was able to view an older version of the site before the change locally by checking out an older commit on main and running the local setup. Here is a screenshot:
![Screenshot 2023-02-10 at 10 31 39 AM](https://user-images.githubusercontent.com/56164590/218170330-52fae980-f4cb-4cf7-9ebf-61f6db9451a4.png)

Note that this only still works because the older results data file formats are still being generated by the results-analysis scripts.

**Comment by jgraham** [comment]
I don't know of any work that's still planned here, so closing the issue.
