### ISSUE TITLE
Retrospective: proposer experience

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#285]
In https://github.com/web-platform-tests/interop/issues/274 we're doing a retrospective on the Interop 2023 process on launch, as input to Interop 2024.

I'd like to solicit the feedback from those of you who submitted and advocated for proposals, in particular you who that aren't employed by one of the organizations that form the interop team.

That is: @Afif13 @agusterodin @alexlehner86 @AmitMY @AshleyScirra @astearns @BearCooder @brandonmcconnell @hunterloftis @jackhp95 @jsnkuhn @legowerewolf @LeviPesin @myakura @nilaallj @potch @ramiy @romainmenke @scottkellum @svoisen @tapananand @thlinard @Westbrook @ydaniv @ygupta81

Anything that you think worked well or not so well, and any ideas for improvement, would be welcome feedback.

I'll not get involved with the discussion unless asked, but will try to summarize in ~2 weeks.

If you have private feedback, feel free to reach out to anyone you know to be involved with this project in private (DMs, email, chat, etc.) and ask them to share with the rest of the interop team. You can find some email addresses with `git log` in a checkout of this repo.

**Comment by romainmenke** [comment]
The combination of submitting a proposal here and writing more tests in WPT worked well for me.

Adding tests in WPT was not a requirement for submitting proposals, but it helped me to have a better understanding and to better explain the interop issue I was trying to get fixed.

It seemed there was a point where discussion stopped on individual issues and then suddenly it was decided which proposals were included. So I was unsure what the state of my proposal was.

Might be nice to have some labels for :
- we have sufficient information to make a decision later
- we don't have sufficient information

It is very nice that this process is in the open and that we can engage and submit proposals 🙇

**Comment by legowerewolf** [comment]
As the one who proposed #169: Temporal, I'm satisfied with the way the process went. Would I be more satisfied if it had been selected? Oh yeah. But understanding why it wasn't isn't a bad consolation prize.

**Comment by ramiy** [comment]
Hi @foolip 

First of all, I like the fact that browsers make decisions based on user research (in this case web developers). I also like the fact that the process was transparent. I would like to see the list of proposals that were not accepted, and the reason why they were rejected.

I don't know why, but for some reason I thought I could make one suggestion. In retrospect, I would make a few more suggestions. Next year I will send several proposals (starting with CSS scrollbars and line-clamp).

Personal experience at work:

I work for a company that serves tens of millions of active websites that build their websites using our product. While our first impulse is to use native solutions, due to browser incompatibilities we are forced to create custom solutions or use inflated libraries. Unfortunately, the internet is slower because of the browsers themselves.

Over the years, cross-browser incompatibilities required us to use a lot of custom JS and external libraries. I currently handle several performance and accessibility initiatives, and every time we replace old JS code with simple CSS, we see performance improvements and reduced load times. All these changes are cumulative.

The interop project has a huge potential to improve website performance and make the internet faster. The more features will become cross-browser supported, the less custom code we will use.

I'm excited about the future. Especially when I saw the size of the list for 2023.

**Comment by jsnkuhn** [comment]
Would also like to call out how nice it was to get responses as to why things that didn't make the cut this year were not chosen. With all of the work I'm sure this process must be I wouldn't have been surprised to not get any response for the things that didn't make it in. I appreciate you taking the time to give an explanation.

One of the things that I proposed that did make it in this time, css `image-set`, was included with some other bugs as part of the "Web Compat 2023" category. I've read the description provided for this category but must admit I am still not sure why something goes in "Web Compat 2023" vs getting specifically called out as a focus area on its own. I've already had interactions with people who were confused when I said `image-set` made the cut this year because they didn't see it called out specifically on the list.

**Comment by foolip** [comment]
@ramiy asked:

> I would like to see the list of proposals that were not accepted, and the reason why they were rejected.

You can see all 87 proposals in [this project](https://github.com/orgs/web-platform-tests/projects/2/views/1), and filter that to the [34 included](https://github.com/orgs/web-platform-tests/projects/2/views/1?filterQuery=label%3Aaccepted) + [53 excluded](https://github.com/orgs/web-platform-tests/projects/2/views/1?filterQuery=-label%3Aaccepted) proposals. If you click through to the comments and search for "Posted on behalf of the Interop team" you'll find the joint feedback from the interop team.

**Comment by AshleyScirra** [comment]
Overall I feel this is a great project and the process went well. However in the interest of improving it, here is one thought. As an experienced web developer submitting proposals, I can point to which APIs are affected, test cases demonstrating browser incompatibilities, and corresponding browser bug reports. However after posting a proposal sometimes I was asked questions about the relevant WPT area or specifications. I didn't really feel like I was the best person to answer those questions - these seemed more like questions for specification authors or browser developers, but it felt like I was still the one who was expected to answer them. So I had a go at answering them anyway, but sometimes this resulted in a long-winded or confusing conversation, because I was forced to talk about something I felt I didn't really know that much about.

**Comment by romainmenke** [comment]
https://github.com/web-platform-tests/interop/issues/285#issuecomment-1427873526

> So I had a go at answering them anyway, but sometimes this resulted in a long-winded or confusing conversation, because I felt I was forced to talk about something I felt I didn't really know that much about.

It might be interesting if someone was assigned to a proposal to help the submitter advocate for it. Maybe only if the submitter requests this, but clearly documented that this is an option.

**Comment by ydaniv** [comment]
Hey all,

First of all this is a wonderful and blessed project, thanks for all the work put into this!  Much appreciated!

Second, my proposal started with splitting from #147 after receiving feedback that its scope is too broad.
So I opened #214. This was answered by a comment that SVG received medium level of interest from developers in the "State of _**CSS**_" survey. While being a good method for CSS-related features, it's a bit questionable for gathering precise feedback about SVG. It can mostly (if not only) tell us about level of interest in the _**intersection**_ of CSS and SVG.

After that, I'm afraid I haven't received any other comments/feedback/questions, so that was it.

Need to also point out that my proposal was for **investigation**, mostly to get some talks out in the open about state and future of SVG.

I guess my conclusion here is that SVG is in a very low priority for browser vendors, but it would be great to have a transparent feedback on how/where/if things can progress.

**Comment by nairnandu** [comment]
Thank you for all the feedback! Please keep it coming.

Taking a stab at summarizing the feedback thus far:

**What's working well?**

- Authoring more tests in WPT as part of submitting a proposal works well. It helps the author to build a better understanding and explain the interop issue better.
- Knowing why a proposal is not included, for the current iteration of Interop, is helpful
- Decision making based on user research (web developers)

**What could we improve?**

- Need more visibility on the "current status" for a proposal (maybe via a label)
- More visibility on proposals that were excluded, for the current iteration of Interop, and the reasoning for the same
- More clarity on grouping of proposals into focus areas would be helpful (e.g.: WebCompat)
- Proposal authors might require support/guidance, on standards and WPT as an example, to build a strong proposal
- Especially for proposals that are excluded, recommendations (transparent feedback) on next steps would be helpful to ensure progress

**Comment by foolip** [comment]
Thank you @nairnandu for summarizing!

**Comment by BearCooder** [comment]
Some idea/suggestion for future Interop:
What about creating the following dev survey: 

Pull a list from Can I use with all features that are at least supported by one main browser but not in the others.

Make a list and ask specifically in the survey about the features what developers want to see to get wide browser support and ask why/whats their usecase/why its missing etc.

I believe this way we can get a better overwiev what people would like to see supported.
What do you think? @foolip

**Comment by foolip** [comment]
Coming back from a few months leave here...

@myakura we've just opened up proposals for Interop 2024, and made quite a few changes to the proposal template. I hope they're even more helpful now! I agree that https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md is rather bureaucratic and dry. This year https://github.com/web-platform-tests/interop/pull/390 will flesh it out quite a bit, but it will still be mostly for the interop team. I'm not sure it can be usefully summarized except as "the interop team decides by an elaborate evaluation process and ultimately consensus."

@BearCooder I like how you're thinking! In surveys like State of CSS we've asked developers about problematic features, both in freeform text, and with multiple select. But I've never seen a survey where developers can see and filter all existing features. Caniuse unfortunately is missing many new (and old) features, but https://github.com/web-platform-dx/web-features has the goal of covering the whole platform, and could perhaps be used for multi-select questions in surveys in the future.

Thanks for the feedback everyone! I'll close this issue now, because Interop 2024 is upon us 😅
