### ISSUE TITLE
Inconsistent end-point for Interop pages

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/interop#286]
https://wpt.fyi/interop-2022 shows a graph ending at the end of 2022, but the scores shown above are for the latest run (currently 2023). These should probably be consistent.

This difference is more stark if you look at https://wpt.fyi/interop-2021, where the scores are notably higher than the graph shows.

Per https://twitter.com/olwinfr/status/1618721146802950144, this does appear to be causing some actual confusion among people looking at the dashboard, so we should ensure it's clear what data is being presented.

cc @web-platform-tests/interop

**Comment by foolip** [comment]
@DanielRyanSmith there is one more complication that specifying an end date doesn't deal with, and that's changes in the test lists that happen after the year has ended.

I think what we'll need to do is go back and see what the test lists were and the end of 2021 and 2022, and freeze those lists somewhere. Then we could keep running the scripts because they should always produce the same output, or just take a frozen copy of the output and put in a storage bucket.

**Comment by foolip** [comment]
We have the same problem for Interop 2023 as well now, where the graph ends in December but we kept updating the scores until Jan 31.

**Comment by foolip** [comment]
This is resolved now with how we're archiving the dashboard for each year:
https://wpt.fyi/interop-2021
https://wpt.fyi/interop-2022
https://wpt.fyi/interop-2023
