### ISSUE TITLE
[motion-1] Add new tests for <basic-shape>

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#327]
### Test List

[offset-path-shape-circle-001.html](https://wpt.fyi/results/css/motion/offset-path-shape-circle-001.html?label=experimental&label=master&aligned)
[offset-path-shape-circle-002.html](https://wpt.fyi/results/css/motion/offset-path-shape-circle-002.html?label=experimental&label=master&aligned)
[offset-path-shape-circle-003.html](https://wpt.fyi/results/css/motion/offset-path-shape-circle-003.html?label=experimental&label=master&aligned)
[offset-path-shape-circle-004.html](https://wpt.fyi/results/css/motion/offset-path-shape-circle-004.html?label=experimental&label=master&aligned)
[offset-path-shape-ellipse-001.html](https://wpt.fyi/results/css/motion/offset-path-shape-ellipse-001.html?label=experimental&label=master&aligned)
[offset-path-shape-ellipse-002.html](https://wpt.fyi/results/css/motion/offset-path-shape-ellipse-002.html?label=experimental&label=master&aligned)
[offset-path-shape-ellipse-003.html](https://wpt.fyi/results/css/motion/offset-path-shape-ellipse-003.html?label=experimental&label=master&aligned)
[offset-path-shape-ellipse-004.html](https://wpt.fyi/results/css/motion/offset-path-shape-ellipse-004.html?label=experimental&label=master&aligned)
[offset-path-shape-inset-001.html](https://wpt.fyi/results/css/motion/offset-path-shape-inset-001.html?label=experimental&label=master&aligned)
[offset-path-shape-inset-002.html](https://wpt.fyi/results/css/motion/offset-path-shape-inset-002.html?label=experimental&label=master&aligned)
[offset-path-shape-polygon-001.html](https://wpt.fyi/results/css/motion/offset-path-shape-polygon-001.html?label=experimental&label=master&aligned)
[offset-path-shape-polygon-002.html](https://wpt.fyi/results/css/motion/offset-path-shape-polygon-002.html?label=experimental&label=master&aligned)
[offset-path-shape-polygon-003.html](https://wpt.fyi/results/css/motion/offset-path-shape-polygon-003.html?label=experimental&label=master&aligned)
[offset-path-shape-rect-001.html](https://wpt.fyi/results/css/motion/offset-path-shape-rect-001.html?label=experimental&label=master&aligned)
[offset-path-shape-rect-002.html](https://wpt.fyi/results/css/motion/offset-path-shape-rect-002.html?label=experimental&label=master&aligned)
[offset-path-shape-xywh-001.html](https://wpt.fyi/results/css/motion/offset-path-shape-xywh-001.html?label=experimental&label=master&aligned)
[offset-path-shape-xywh-002.html](https://wpt.fyi/results/css/motion/offset-path-shape-xywh-002.html?label=experimental&label=master&aligned)

### Rationale

There is only one test to cover the functionality of the basic-shapes for motion path. I propose to add these tests and delete [offset-path-shape.html](https://wpt.fyi/results/css/motion/offset-path-shape.html?label=experimental&label=master&aligned) as it's incorrect (the sizes of the inset are resolved against its own size, not the reference box).

**Comment by danielsakhapov** [comment]
@BorisChiou @nmoucht FYI

**Comment by BorisChiou** [comment]
Gecko doesn't support basic shape for motion, so I'm OK with landing these tests (and may verify again when I work on the gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1598156)

**Comment by gsnedders** [comment]
In aggregate: [this wpt.fyi query](https://wpt.fyi/results/css/motion?label=master&label=experimental&aligned&q=offset-path-shape.html%20or%20offset-path-shape-circle-001.html%20or%20offset-path-shape-circle-002.html%20or%20offset-path-shape-circle-003.html%20or%20offset-path-shape-circle-004.html%20or%20offset-path-shape-ellipse-001.html%20or%20offset-path-shape-ellipse-002.html%20or%20offset-path-shape-ellipse-003.html%20or%20offset-path-shape-ellipse-004.html%20or%20offset-path-shape-inset-001.html%20or%20offset-path-shape-inset-002.html%20or%20offset-path-shape-polygon-001.html%20or%20offset-path-shape-polygon-002.html%20or%20offset-path-shape-polygon-003.html%20or%20offset-path-shape-rect-001.html%20or%20offset-path-shape-rect-002.html%20or%20offset-path-shape-xywh-001.html%20or%20offset-path-shape-xywh-002.html).

**Comment by foolip** [comment]
@gsnedders @nt1m can either of you get a position for WebKit on this?

**Comment by BorisChiou** [comment]
I just noticed these two tests:
1. [offset-path-shape-circle-002.html](https://github.com/web-platform-tests/wpt/blob/master/css/motion/offset-path-shape-circle-002.html)
2. [offset-path-shape-ellipse-002.html](https://github.com/web-platform-tests/wpt/blob/master/css/motion/offset-path-shape-ellipse-002.html)

Their expectations (i.e. xxx-ref.html) seem incorrect to me.

Per css-shape spec (https://drafts.csswg.org/css-shapes-1/#typedef-shape-radius), for `<shape-radius>`:
> Defines a radius for a circle or ellipse. If omitted it defaults to closest-side.

So they are equal to `circle(closest-side)` and `ellipse(closest-side)`. The closest-side in the test for `circle()` is `200px`, so the `translate()` in its ref file is something like `translate(450px, 150px)`, right?

Also, I noticed there are some floating-point numbers used in the xxx-ref files, e.g. [offset-path-shape-ellipse-003-ref.html](https://github.com/web-platform-tests/wpt/blob/master/css/motion/offset-path-shape-ellipse-003-ref.html). I may update thest tests to avoid using so many floating-point numbers in the xxx-ref files. Also, I may add more fuzzy expectations in these tests (for `circle()` and `ellipse()`) for Gecko.

(Note: I expect the fuzzy happens because Gecko uses a different way to handle sub-pixel anti-alias, and the arc calculation makes the angles of the tangent vectors have some minor differences. However, the visual results are almost identical.)

**Comment by danielsakhapov** [comment]
@BorisChiou 

Hi! Thanks for your comment!

1. The nuance with this test is [here](https://drafts.fxtf.org/motion/#valdef-offset-path-basic-shape):

> If [circle()](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-circle) or [ellipse()](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-ellipse) is used, and an explicit center position is not given, they default to using the [offset starting position](https://drafts.fxtf.org/motion/#offset-starting-position), rather than their standard default.

That's why the box ends up at the containing block's top left corner with zero radius, only moved by -50px to match it's center.

2. If you could update tests to have integer numbers, it would be great! I just couldn't find anything integer to test rotation on the circle and ellipse.

3. I'm absolutely fine with fuzziness in the motion path case!

**Comment by BorisChiou** [comment]
Hi @danielsakhapov. Thanks for this explanation. However, I'm still confused about the "zero radius" in
> That's why the box ends up at the containing block's top left corner with zero radius, only moved by -50px to match it's center.

The spec just mentions we use the [offset starting position](https://drafts.fxtf.org/motion/#offset-starting-position) as it central point (See https://drafts.fxtf.org/motion-1/#offset-position-property).
> Currently, [circle()](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-circle) and [ellipse()](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-ellipse) [offset paths](https://drafts.fxtf.org/motion-1/#offset-path) use this position as their center, if the center position is omitted from their arguments. This is not an initial position, obviously.

So should we still use the default radius, which is `closest-side`. i.e. the translate is something like `translate(-50px + 200px, -50px)` = `translate(150px, -50px)` (for offset-distance:0)? (Though https://github.com/w3c/fxtf-drafts/issues/504 haven't be addressed yee in the spec.)

**Comment by BorisChiou** [comment]
I hidden the comment because now I understand the reason. For `circle()`, the default `offset-position` makes the center of the circle be top left, so the radius, `closest-side`, is 0px. That's why the final translate is `translate(-50px, -50px)`.

**Comment by tabatkins** [comment]
No, not quite. It makes it be the top left *of the transformed element* (its pre-transform position). Now, in this case, that happens to also be the top left of the containing block, because that's just how the element is positioned. Then we resolve closest-side against the containing block and get a 0 radius.

If the square had a margin on it, or the container had padding, or anything to not make those two corners coincident, then we'd get a non-zero radius out of it.

(And btw, I had some pending edits from <https://github.com/w3c/fxtf-drafts/issues/504> that I've just applied, so it would be good to get some tests for that as well - offset-position can now be `normal`, which means you use the normal defaulting rules for an omitted position as specified by the Shapes spec.)

**Comment by BorisChiou** [comment]
Thanks for the "NOTE" to explain the definition of the _box_ for `offset-position:auto` in the spec. :)

**Comment by tabatkins** [comment]
If it makes you feel better, I actually wrote that text *before* seeing your comment; it just felt like something that should be made more explicit. ^_^

**Comment by nmoucht** [comment]
> @gsnedders @nt1m can either of you get a position for WebKit on this?

I don't have any objections to adding these tests.

**Comment by danielsakhapov** [comment]
thanks all, closing the issue

**Comment by BorisChiou** [comment]
BTW, I just noticed [offset-path-shape-xywh-002.html](https://github.com/web-platform-tests/wpt/blob/master/css/motion/offset-path-shape-xywh-002.html) may be incorrect. It seems Blink uses the height of its reference box to resolve the percentage value of the width of the transformed box:
https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:third_party/blink/renderer/core/style/basic_shapes.cc;l=253;drc=80833aef0b4fff4978b49865bb95a7497f200c71.

Therefore, I'm updating this test file in Gecko's bug right now (https://bugzilla.mozilla.org/show_bug.cgi?id=1786160).
