### ISSUE TITLE
Add css/selectors/invalidation/defined-in-has.html to :has() focus area

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#349]
### Test List

css/selectors/invalidation/defined-in-has.html

### Rationale

WebKit bug, test that might be useful for Firefox implementation too

**Comment by zcorpan** [comment]
cc @emilio

**Comment by foolip** [comment]
This test doesn't show up in the default view because of https://github.com/web-platform-tests/wpt/issues/40085, but there are results from Chrome and Firefox:
https://wpt.fyi/results/css/selectors/invalidation/defined-in-has.html?run_id=5174949528993792&run_id=5070050287943680

@lilles can you review this test, is it OK to add to Interop 2023?

**Comment by emilio** [comment]
Sure, seems fine.
