### ISSUE TITLE
Remove css/css-flexbox/webkit-box-vertical-writing-mode.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#355]
### Test List

css/css-flexbox/webkit-box-vertical-writing-mode.html

### Rationale

This is testing legacy flexbox (-webkit-box), not modern flexbox. This test seems out of scope.

**Comment by foolip** [comment]
@davidsgrogan can you review this for Chromium?

**Comment by davidsgrogan** [comment]
-webkit-box is used on a nontrivial amount of pages still today [1] AND the legacy `-webkit-*` properties are included in the modern spec AND all 3 engines implement `-webkit-box`, so I don't think `-webkit-box` tests are out of scope for the flexbox focus area in and of themselves.

But I'm ok with dropping this test because only a vanishingly small amount of existing pages use -webkit-box in non-horizontal writing modes AND we all want to discourage future use of -webkit-box.

I also want to point out that WebKit is the last engine which has two different layout classes for `flex`/`-webkit-box`. It'd be good to converge on other engines at some point which internally map to the same flexbox engine. That would eliminate bunch of differences, including the difference demonstrated by the test in question.

[1] We see pages accidentally place the wrong order for the display value, which partly explains this, e.g.
```
display: flex;
display: -webkit-box;
```

**Comment by dholbert** [comment]
I can review from Firefox if needed -- dropping the test seems fine, and also +1 to everything that @davidsgrogan said.
