### ISSUE TITLE
Remove wpt/webgl/idlharness.any.html & idlharness.any.worker.html from Interop list

### ISSUE THREAD

**Issue by yiyix** [web-platform-tests/interop#363]
### Test List

[wpt](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas%20chrome%3A%21ok%20chrome%3A%21pass) /[webgl](https://wpt.fyi/results/webgl?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas%20chrome%3A%21ok%20chrome%3A%21pass)/[idlharness.any.html](https://wpt.fyi/results/webgl/idlharness.any.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas%20chrome%3A%21ok%20chrome%3A%21pass)
[wpt](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas%20chrome%3A%21ok%20chrome%3A%21pass) /[webgl](https://wpt.fyi/results/webgl?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas%20chrome%3A%21ok%20chrome%3A%21pass)/[idlharness.any.worker.html](https://wpt.fyi/results/webgl/idlharness.any.worker.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas%20chrome%3A%21ok%20chrome%3A%21pass)

### Rationale

These two tests are exercising the corner cases of the WebGL specification related to the prototype chain of JavaScript wrappers. The issues they revealed have existed for 10 years and have not disturbed any web developers. Note that no current browser passes these tests. These tests are not included in the WebGL conformance suite at https://github.com/KhronosGroup/WebGL as well.

Rather than churn all existing WebGL implementations, the WebGL working group thinks these tests should be removed from the Interop 2023 suite. WebGL working group also suggested that future WebGL tests be proposed for inclusion in the WebGL conformance suite itself, before being added to the Interop 2023 suite.

**Comment by nairnandu** [comment]
@jgraham @zcorpan  can you review for Gecko?

@gsnedders @nt1m can you review for WebKit?

**Comment by gsnedders** [comment]
> Rather than churn all existing WebGL implementations, the WebGL working group thinks these tests should be removed from the Interop 2023 suite. 

Does this imply that you think no implementation should move to match what is currently spec'd, because that would be additional churn? If so, does the WG believe it should change the spec to match existing implementations?

> WebGL working group also suggested that future WebGL tests be proposed for inclusion in the WebGL conformance suite itself, before being added to the Interop 2023 suite.

There's relatively few tests in WPT for WebGL; from memory @Ms2ger had added them there at a point when submitting things to the Khronos test suite was relatively burdensome. If someone wants to move those to the WebGL test suite, I doubt there would be complaints?

The idlharness tests probably make sense to keep in WPT, given we have all the machinery to both auto-update IDL fragments and `idlharness.js` itself lives in WPT?

**Comment by Ms2ger** [comment]
It seems like a rather unfortunate situation for the working group to request by back channels that implementers ignore the specification it publishes. I have no opinion on the inclusion in the interop list, but tests matching the actual specification should definitely remain in wpt.

(At least some of the failures seem to flag that the IDL in the specification is invalid, so that needs fixing anyway.)

**Comment by kkinnunen-apple** [comment]
What are the concrete problems?
With a quick glance, I can see:

1. WebGLObject is not in the global object
Filed: https://github.com/KhronosGroup/WebGL/issues/3542

2. Overload methods are reported as duplicate members: 

Is it a WebGL spec problem or IDL test harness problem?

```
IdlArray.prototype.are_duplicate_members = function(m1, m2) {
    if (m1.name !== m2.name) {
        return false;
    }
    if (m1.type === 'operation' && m2.type === 'operation'
        && m1.arguments.length !== m2.arguments.length) {
        // Method overload. TODO: Deep comparison of arguments.
        return false;
    }
    return true;
}
```

**Comment by zcorpan** [comment]
Excluding these from Interop 2023 is OK for Mozilla.

**Comment by yiyix** [comment]
>Does this imply that you think no implementation should move to match what is currently spec'd, because that would be additional churn? If so, does the WG believe it should change the spec to match existing implementations?

I think the spec needs to be updated to match the real implementation

> There's relatively few tests in WPT for WebGL; from memory @Ms2ger had added them there at a point when submitting things to the Khronos test suite was relatively burdensome. If someone wants to move those to the WebGL test suite, I doubt there would be complaints?

Adding @kenrussell to give more insights on this

> The idlharness tests probably make sense to keep in WPT, given we have all the machinery to both auto-update IDL fragments and idlharness.js itself lives in WPT?

I also believe those tests should continue live in WPT, they are catching the errors as they are supposed to. But I don't think they need to be in the interop 2023 test list as they haven't disturbed any developers in last 10 years.

**Comment by kenrussell** [comment]
It would be fine to move the few wpt tests for WebGL into the conformance suite at https://github.com/KhronosGroup/WebGL .

The WebGL working group would like to align all implementations with the specification, just without the time pressure of doing this in Interop 2023. Per @kkinnunen-apple 's comment above and looking at https://webidl.spec.whatwg.org/#idl-overloading , it looks like the Web IDL test harness's definition of illegal overloads is not correct, and that it's flagging some legal overloads in the WebGL specification. This needs to be studied in more depth and ironed out.

**Comment by gsnedders** [comment]
> > Does this imply that you think no implementation should move to match what is currently spec'd, because that would be additional churn? If so, does the WG believe it should change the spec to match existing implementations?
> 
> I think the spec needs to be updated to match the real implementation

FWIW, given this came up in the meeting: from a WebKit point of view we are fine with dropping these tests from Interop 2023, our primary concern was that the WG is actually tracking what appears to be interoperably failing—rather than just filing an issue here saying we shouldn't score that.

Given @kkinnunen-apple filed https://github.com/KhronosGroup/WebGL/issues/3542, we're fine with removing this; I just wanted to make sure the WG was actually tracking something for the failure on their side.
