### ISSUE TITLE
MouseEvent.layerX/layerY

### ISSUE THREAD

**Issue by emilio** [web-platform-tests/interop#37]
**Description**
The `MouseEvent.layerX` and `layerY` properties are implemented everywhere but right now they're not interoperable and cause compat pain.

Right now, they depend on internal layerization details in WebKit and Blink (which are different and subject to change). Gecko's definition is somewhat reasonable but of course doesn't match those.

**Bug reports**
https://github.com/webcompat/web-bugs/issues/94500 is a fairly-recent one.

**Specification**
None (that's the problem!) but I have a reasonable (I think) proposal [here](https://github.com/w3c/uievents/issues/135#issuecomment-981613602).

**Tests**
None (also a problem!) but I'm happy to write some if we agree on a definition.

This is a bug to include in #9

Note that I wasn't sure this was suitable for the compat-2022 effort because of the lack of spec right now, but I think it's a relatively minor feature such as that it shouldn't be hard to come up with a proper spec during the next months.

**Comment by foolip** [comment]
Per https://github.com/web-platform-tests/interop-2022/issues/39#issuecomment-991001758 we're not including this in Interop 2022, due to the lack or spec and tests.

However, convergence on this is a good idea. The group needs to decide if we're going to track that work as part of Interop 2022 or not. Regardless, next steps seem to be responding to https://github.com/w3c/uievents/issues/135#issuecomment-981613602.
