### ISSUE TITLE
Add min/max function tests 

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#377]
### Test List

https://wpt.fyi/results/css/css-values?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=minmax

### Rationale

Some differences in serialization across browsers

**Comment by nt1m** [comment]
@emilio @tiaanl Can you help review for Gecko?

@xiaochengh / @nairnandu Can you help review for Chromium?

**Comment by emilio** [comment]
+1 from me

**Comment by xiaochengh** [comment]
I'm wondering about `css/css-values/minmax-percentage-serialize.html`, which currently asserts that percentage comparisons are not simplified at parse time.

The [spec](https://www.w3.org/TR/css-values-4/#calc-simplification) however seems a bit vague/inconsistent about this.

At one point, it says:

> [Internal representations](https://drafts.css-houdini.org/css-typed-om-1/#css-internal-representation) of [math functions](https://www.w3.org/TR/css-values-4/#math-function) are eagerly simplified to the extent possible

At another point, as a non-normative note, it says:

> If a percentage is left at this point, it will usually block simplification of the node, since it needs to be resolved against another value using information not currently available... This includes operations such as "min", since percentages might resolve against a negative basis

However, I find this note not very convincing, because % resolved against a negative value is a very rare case that's currently possible only in the `background-position` property. So percentage comparisons actually almost never blocks the simplification.

**Comment by xiaochengh** [comment]
Other tests LGTM

**Comment by nt1m** [comment]
I was actually wondering the same thing looking at `css/css-values/minmax-percentage-serialize.html` the other day

**Comment by nairnandu** [comment]
@nt1m closing this one as the change is merged.

**Comment by nt1m** [comment]
I'm reopening to discuss `css/css-values/minmax-percentage-serialize.html`

**Comment by Loirooriol** [comment]
Would be good to have some test for https://github.com/w3c/csswg-drafts/issues/9631
