### ISSUE TITLE
Agenda, Aug 10th 2023

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#391]
Here is the proposed agenda for the Aug 10rd meeting:
* Interop 2023 - Blocked dashboard updates
* Interop 2024 [Backlog](https://docs.google.com/spreadsheets/d/1E-V-0HTEAIKZYmgfdE0Uiiu-K3_7tVUZOKUCPQ6i75A/edit#gid=0)
  * Proposal selection process
  * Proposed timeline https://github.com/web-platform-tests/interop/issues/384
  * Updated focus area proposal template https://github.com/web-platform-tests/interop/pull/385
* Interop 2023 - [Test change proposal](https://github.com/web-platform-tests/interop/issues?q=is%3Aissue+is%3Aopen+label%3Atest-change-proposal) backlog.

**Comment by meyerweb** [comment]
**Dashboard**

James: first agenda item is the dashboard
…2023 dashboard has no updates for experimental builds since 31 July and none from stable builds some time in the middle of July
…I believe the stable build one is a Chrome driver issue, so now it’s downloading the wrong driver
…the experimental problem appears to be with Safari
…so in addition to Azure problem, we’re having the Safari driver failing to start
…been furiously restarting builds, and they keep failing due to various bugs
…Sam, were you looking into the Safari issue?
Sam: I have a tentative plan by increasing the allowable number of restarts via an Azure command line argument
James: I’ll ask on Matrix why you think that’s going to work
Sam: I think it’s just randomly failing to start
James: Okay then.  Let me know when you have a PR for that.
Sam: I’m also confused why the dashboard didn’t update a couple of days ago
James: That one happened because I’ve been retriggering things
…Also there’s a bug in the dashboard to due with runs happening either side of midnight
…I believe Daniel’s going to look into this
Sam: I feel like there’s a PR about this, it’s certainly something we’ve come across before
James: A link would be great

**Comment by meyerweb** [comment]
**2024 process**

James: Moving on to the 2024 process
…We have a list of things blocking the 2024 launch
…ETA was today, but I’m guessing that’s not going to happen due to not having representation from everyone
…First thing is, proposal selection process
…Apple was going to propose something for that, what’s the status?
Sam: There’s a PR
James: I did not see that PR
Sam: Doesn’t make sense to discuss if nobody’s looked at it
Brian: I looked at it a little bit
James: Could you give a rough overview, Sam?
Sam: For the focus area selection, we start off a very quick elimination round
…Essentially we exclude anything that doesn’t meet some very basic criteria
…If there’s disagreement about something meeting those, we leave it in
…In the second round, organizations choose their top ten proposals to include
…That’s used to filter down further, carrying forward anything anyone chose
…In the final round, choose by collective vote with veto blocking
Brian: There’s a few places you mention Khronos; I was wondering what you had in mind with that
Sam: Nothing; I think the list of groups was largely copy-pasted from the Interop 2023 proposal template
Brian: The first time I see it, it’s under requirements and the next sentence says it has to have high-quality tests in WPT or Test262
…Khronos has their own conformance tests
James: The practical problem we have with non-WPT tests, which is we can’t score them
Brian: Right, that’s what drew my attention
…I think we mean “as long as they’re testable in WPT”
Sam: I think this was a copy-paste
…We decided to allow people to propose things tested in other conformance suites, though we can’t score them
James: I think Philip was confident we could scramble structure to make things possible
…We ended up doing a one-off for a Test262 topic area where we copied over tests to WPT rather than pull data directly
…I’m okay with this being in the proposal
…If someone proposes somethiing from ECMAscript, there’s more uncertainty there
…We’d have to do more work to score directly
…I think we’d just copy tests over, which isn’t ideal
…We’re open to making a plan to score directly from other test bases
Boaz: I’ve been talking to Philip about finding a new maintainer for Test262 and bring things over to WPT, so maybe that will help one day
James: From my point of view, I’m in favor of that in general, but not sure we can do it in time to select proposals in October
James: Next question is, do we want to discuss the proposal selection proposal further, or take an action item for people to read this and properly discuss it next meeting?
Boaz: I think read it and discuss next time, also send a link to the mailing list
James: Good idea

**Comment by meyerweb** [comment]
**Timeline**

James: Next up is timeline
…Which Sam’s proposal includes, though it shortens the period by a week
Sam: It’s possible I messed up when doing the timeline
James: So the idea in the PR is that we’d have 3 weeks to ask for proposals, and then a week to ask for changes
Sam: Yes
James: That makes some sense to me
…Seems like a soft deadline
…The main constraint is if you hear about the proposal at the start of the open call period, you have time to write a proposal
…It seems like we have soft consensus on the launch date being 14 September, with the selection process finished by the end of November

**Comment by meyerweb** [comment]
**Proposal template**
James: Currently the template is only for topic areas
…Are we still accepting proposals for investigation efforts, or are people assuming there won’t be any?
Boaz: I have a strong feeling that based on the way the accessibility investigation is going, there will be appetite for it next year
James: So there’s an action item here to update the investigation area template
…For focus areas, did people have a chance to look at the PR?
Boaz: I thought it was cool there were privacy and accessibility rationales
…I also like being able to see them rendered, Github forms are cool
James: If other people don’t have immediate thoughts, it would be good if by next week we all had this reviewed
…So, action item on the group is: please review the proposal template by next week so we can be ready to merge it
…I’ll create one for an investigation template
…The question is if people are prepared to commit time to investigation, if that makes sense
…Anything else in terms of 2024 to discuss?  We still have an ETA/deadline in two weeks to publish the selection process
…That’s not currently assigned to anyone, and I don’t want to volunteer for scheduling reasons
…Doing this may depend on feedback to the Apple PR
