### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by stof** [web-platform-tests/interop#423]
### Description

The popover attribute allows creating dropdown UIs using platform features, solving the case of a dropdown being cut by the overflow behavior of the container (as it goes in the top layer) and without requiring JS to trigger it (thanks to `popovertarget`.

This is already implemented in Blink and is partially implemented in Webkit. Reaching interop would allow relying on it.
Thus, due to the top-layer behavior, it is hard (or maybe even impossible) to polyfill this feature.

### Specification

https://html.spec.whatwg.org/multipage/popover.html#the-popover-attribute

### Tests

https://wpt.fyi/results/html/semantics/popovers?label=master&label=experimental&aligned

Maybe also https://wpt.fyi/results/close-watcher/popover-closewatcher.html?label=master&label=experimental&aligned and https://wpt.fyi/results/close-watcher/popover-closewatcher-multiple-plus-free.html?label=master&label=experimental&aligned but not sure about them

### Current Implementations

- [X] Blink
- [ ] Gecko
- [x] WebKit

### Standards Positions

https://github.com/mozilla/standards-positions/issues/698

https://github.com/WebKit/standards-positions/issues/74

### Browser bug reports

https://bugzilla.mozilla.org/show_bug.cgi?id=1808823
https://bugs.chromium.org/p/chromium/issues/detail?id=1307772
https://bugs.webkit.org/show_bug.cgi?id=250171

**Comment by foolip** [comment]
cc @stubbornella @mfreed7 @una

**Comment by nt1m** [comment]
WebKit implements everything except `popover=hint`, which does not have a spec yet (hence isn't eligible for Interop 2024).

**Comment by mfreed7** [comment]
> `popover=hint`, which does not have a spec yet (hence isn't eligible for Interop 2024).

I agree with this part, with the caveat that we've got [a spec PR open now](https://github.com/whatwg/html/pull/9778) to add `popover=hint` behavior. I'd love to get that reviewed and then add it to Interop 2024 if that's still possible!

**Comment by foolip** [comment]
In preliminary results for State of HTML 2023, popover was the most common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?" See https://github.com/web-platform-tests/interop/issues/550 for details.

**Comment by lukewarlow** [comment]
https://bugs.webkit.org/show_bug.cgi?id=263081 - This is an example of an interop bug with Popover implementations.

**Comment by nt1m** [comment]
Someone would need to write a WPT for it

**Comment by foolip** [comment]
Also from State of HTML preliminary results, Popover was the [feature that respondents expressed the most interest for](https://github.com/web-platform-tests/interop/issues/550#issuecomment-1777758744). Note that this wasn't freeform, it's based on the features the survey asked about experience and sentiment for.

**Comment by LeaVerou** [comment]
@foolip You're burying the lede a little bit 😅 Popover came up **all over the survey**, in freeform and non-freeform questions. The need for native popovers was probably one of the biggest themes (2nd only after stylability IMO).

### Most interesting known features (not freeform)

Out of the respondents who had **heard** each feature, what % were interested?

<img width="795" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/a9270e2d-4c07-40e1-be12-f672a5bbdf95">

Popover is the first, with 52% of those who hadn't used it selecting that they were interested!

### Most interesting unknown features (not freeform)

Out of the respondents who had **not heard** each feature, what % were interested?

<img width="791" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/90762404-36c5-4d8e-84ac-a34b9e2a1ba8">

46% of people who had not even heard of the Popover API before the survey selected they were interested.

### Top interop pain points

> “Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?”

<img width="860" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/db6f10d0-d95a-45c8-8e65-2f552545191a">

2700 issues / 1755 responses, manually classified

Popover is the first one, occupying almost 10% of all complaints!

## Unable to use for other reasons

> **Which existing HTML features or browser APIs are you unable to use for other reasons (and why)?**
> Good candidates might be existing HTML features that you often have to recreate or augment using JS.

<img width="855" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/b0d63e94-9067-4d8f-bdee-437fcfa551e2">

Popover is 6th here too, despite not really being relevant (since it's not yet supported really). I suspect people misread the questions and entered things that would be more relevant in the question above (i.e. due to browser support)

### Top interactivity pain points (freeform)

> **What are your pain points around dynamic HTML changes?**
> Browser incompatibilities or lack of support, missing features, and other problems you face around interactive elements and behaviors (except forms), DOM manipulation, events, and related APIs.

<img width="793" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/25076ffe-2758-4dad-8183-feb8e039ffa8">

12th most common complaint was related to the lack of popovers.

**Comment by foolip** [comment]
Thank you @LeaVerou for summarizing with nice screenshots!

**Comment by jensimmons** [comment]
Could someone create a link to the tests that will likely be included, without any of `popover=hint`, (since it does not have a spec yet and therefore is not eligible for Interop 2024).

**Comment by mfreed7** [comment]
> Could someone create a link to the tests that will likely be included, without any of `popover=hint`, (since it does not have a spec yet and therefore is not eligible for Interop 2024).

The OP contains the correct link to the tests: https://wpt.fyi/results/html/semantics/popovers?label=master&label=experimental&aligned

I tried, and failed, to come up with a search term that eliminates the tests that end in `.tentative.html`, but wpt.fyi's search syntax is... different than I'm used to. I did verify that all popover tests that use/test non-standard features (including `popover=hint` and anchor positioning) are correctly marked with `.tentative.html`.

**Comment by gsnedders** [comment]
https://wpt.fyi/results/html/semantics/popovers?label=master&label=experimental&aligned&q=not%20is%3Atentative does that.

**Comment by mfreed7** [comment]
> https://wpt.fyi/results/html/semantics/popovers?label=master&label=experimental&aligned&q=not%20is%3Atentative does that.

So simple! Thanks.

**Comment by gsnedders** [comment]
Do [these tests](https://wpt.fyi/results/html/semantics/popovers?label=master&label=experimental&aligned&q=not%20is%3Atentative%20path%3A%2Fhtml%2Fsemantics%2Fpopovers%20anchor) not rely on anchor positioning?

**Comment by mfreed7** [comment]
> Do [these tests](https://wpt.fyi/results/html/semantics/popovers?label=master&label=experimental&aligned&q=not%20is%3Atentative%20path%3A%2Fhtml%2Fsemantics%2Fpopovers%20anchor) not rely on anchor positioning?

Hmm, those are good to highlight. Most rely on just the `anchor` attribute, and not all of anchor positioning. But you're right that none of that is standardized at the moment. We should probably rename those back to .tentative. I'll take care of that...

**Comment by mfreed7** [comment]
https://github.com/web-platform-tests/wpt/pull/43121

**Comment by stof** [comment]
Actually, https://wpt.fyi/results/html/semantics/popovers/popover-invoking-attribute.html?label=experimental&label=master&aligned&q=not%20is%3Atentative contains a bunch of sub-tests that are for `popover=hint` (see the tests with missing results in Safari and Firefox). Those should probably be extracted in a separate tentative test.

**Comment by mfreed7** [comment]
> Actually, https://wpt.fyi/results/html/semantics/popovers/popover-invoking-attribute.html?label=experimental&label=master&aligned&q=not%20is%3Atentative contains a bunch of sub-tests that are for `popover=hint` (see the tests with missing results in Safari and Firefox). Those should probably be extracted in a separate tentative test.

Another good point. In progress: https://github.com/web-platform-tests/wpt/pull/43436

**Comment by stof** [comment]
@mfreed7 thanks.
Looking at those in more details, the test titles in https://wpt.fyi/results/html/semantics/popovers/popover-stacking.html?label=experimental&label=master&aligned make me think that this non-tentative test also includes some sub-tests relying on anchor positioning, that should also be tentative.

**Comment by nt1m** [comment]
As part of this focus area, we should not include tests relating to:
- close watcher
- hints
- anchor attribute
- the overlay property

**Comment by stof** [comment]
https://wpt.fyi/results/html/semantics/popovers/popover-attribute-basic.html?label=experimental&label=master&aligned also seems to mix subtests that should be tentative and subtests that should not. any subtest involving `hint` should be moved to a separate test (marked as tentative) IMO.

**Comment by mfreed7** [comment]
> https://wpt.fyi/results/html/semantics/popovers/popover-attribute-basic.html?label=experimental&label=master&aligned also seems to mix subtests that should be tentative and subtests that should not. any subtest involving `hint` should be moved to a separate test (marked as tentative) IMO.

Thanks for continuing to point these out. I'll look into fixing this one. One note is that the test harness there only tests `popover=hint` if supported by the browser. (That test is fairly large and I really wanted to avoid a full copy/paste to make a "hint-supported" version.) Since the harness just skips tests if `popover=hint` isn't supported, leading to `MISSING` entries on the dashboard, are we sure those get counted in Interop metrics? Or is there a world where we could just skip those for Interop?

**Comment by zcorpan** [comment]
Thank you for proposing Popover for inclusion in Interop 2024.

We are pleased to let you know that this proposal was accepted as part of the Popover focus area. You can follow the progress of this focus area on the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).

For an overview of our process, see the [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you for contributing to Interop 2024!

_Posted on behalf of the Interop team._

**Comment by lukewarlow** [comment]
I'm not sure where is the most appropriate place to raise this so noting here.

[html/semantics/popovers/popover-shadow-dom.html](https://wpt.fyi/results/html/semantics/popovers/popover-shadow-dom.html) - This test is part of interop2024 but has 2 subtests that rely on the anchor attribute which isn't part of interop (nor specced fully afaik).

**Comment by nt1m** [comment]
@mfreed7 Can we get these split out from the test ?

**Comment by zcorpan** [comment]
Thanks @lukewarlow 

> I'm not sure where is the most appropriate place

A "Test Change Proposal" issue: https://github.com/web-platform-tests/interop/issues/new/choose

**Comment by mfreed7** [comment]
> I'm not sure where is the most appropriate place to raise this so noting here.
> 
> [html/semantics/popovers/popover-shadow-dom.html](https://wpt.fyi/results/html/semantics/popovers/popover-shadow-dom.html) - This test is part of interop2024 but has 2 subtests that rely on the anchor attribute which isn't part of interop (nor specced fully afaik).

Yep, I can take care of this. I'll comment back here with a PR once I've had a chance to get it started.

**Comment by mfreed7** [comment]
> Yep, I can take care of this. I'll comment back here with a PR once I've had a chance to get it started.

https://github.com/web-platform-tests/wpt/pull/44679

**Comment by promocot** [comment]
::backdrop not supported css variable!

**Comment by foolip** [comment]
@promocot if you're running into this issue in Chrome, it was fixed in https://chromestatus.com/feature/4875749691752448, in Chrome 122.

https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/backdrop-inherits.html?label=master&label=stable is the relevant test for this, and it looks like it was previously failing (but now passing) in Safari as well.

If you have a problem in the latest version of each browser, please file bug reports in the appropriate bug tracker.

**Comment by promocot** [comment]
Hello, thanks, I tried to update manual my chrome browser, and yep after works, but i found another bug with close popover on clic to icon. For example, I have a HTML

<body>
    <button popovertarget="mypopover" popovertargetaction="show">Show popover</button>
    <button popovertarget="mypopover" popovertargetaction="hide">Hide popover</button>
    <div id="mypopover" popover="">Popover content</div>
</body>

If I click on show button i will see popup, if i click on hide button i will close popup, but if i have structure like this

<body>
    <button popovertarget="mypopover" popovertargetaction="show">
      Show popover
    
    <div id="mypopover" popover="">Popover content
          <button popovertarget="mypopover" popovertargetaction="hide">Hide popover</button>
    </div>
</body>

when i click on show button i will see popup, and if i try to click on the hide button, nothing happens

**Comment by foolip** [comment]
@promocot I see you're missing a `</button>` in that second example, but with or without it still works in my testing, clicking "Hide popover" closes it.

If you have more question please try Stack Overflow, and if you think there are browser bugs file a bug with the appropriate browser.

This issue was to track popover for inclusion in Interop 2024, and is not a good place to ask for help with popover.

**Comment by promocot** [comment]
I am not missing the button in the second example, I place the button inside the popover as a close button. I tested in chrome. Ok i will try to write email for chrome developers

**Comment by promocot** [comment]
I found a problem, in my test case i used attribute for SVG icon not button

  <svg popovertargetaction="hide" popovertarget="mypopover" class="brxe-icon" id="brxe-wvnraz" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"><path d="M18 6L6 18" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path><path d="M18 18L6 6" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path></svg>
  
  but if I add a button with an icon, and set the attribute for the button, all works

**Comment by foolip** [comment]
@promocot that's interesting, do you mean you were trying to add the `popovertarget` or `popovertargetaction` attributes to an SVG element? This probably doesn't work the way the spec is written, can you file an issue at https://github.com/whatwg/html/issues with a code sample of what you were attempting?

**Comment by promocot** [comment]
Yes, I will write about this with a video demo and codeopen
