### ISSUE TITLE
View Transitions Level 1

### ISSUE THREAD

**Issue by lukewarlow** [web-platform-tests/interop#437]
### Description

View Transitions are a new API that web developers are particularly excited about. It would be good to get level 1 of the spec cross browser.

### Specification

https://drafts.csswg.org/css-view-transitions

### Open Issues

All open issues are editorial and don't affect implementations or are aimed at Level 2 of the spec which this issue isn't addressing.

### Tests

https://wpt.fyi/results/css/css-view-transitions

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

https://github.com/WebKit/standards-positions/issues/48 - Supportive

https://github.com/mozilla/standards-positions/issues/677 - Supportive

### Existing Usage

https://chromestatus.com/metrics/css/timeline/popularity/712

**Comment by foolip** [comment]
For survey data and web developer demand, in [preliminary results from State of HTML 2023](https://github.com/web-platform-tests/interop/issues/550), View Transitions was a very common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?"

**Comment by foolip** [comment]
Thank you for proposing View Transitions for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
