### ISSUE TITLE
Scroll-driven Animations

### ISSUE THREAD

**Issue by ramiy** [web-platform-tests/interop#439]
### Description

These scroll-driven animations are currently supported only on one browser engine. It's an amazing feature that reduces a lot of JS, and I personally would love to use it in production websites when all browsers support this feature.

### Specification

https://drafts.csswg.org/scroll-animations/

### Tests

https://wpt.fyi/results/scroll-animations

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

https://groups.google.com/a/chromium.org/g/blink-dev/c/RDKAi9JPHwY/m/Ee9A5LbBAwAJ
https://github.com/mozilla/standards-positions/issues/347
https://github.com/WebKit/standards-positions/issues/152

### Existing Usage

https://chromestatus.com/metrics/css/timeline/popularity/725
https://chromestatus.com/metrics/css/timeline/popularity/726
https://chromestatus.com/metrics/css/timeline/popularity/727
https://chromestatus.com/metrics/css/timeline/popularity/750

https://chromestatus.com/metrics/css/timeline/popularity/665
https://chromestatus.com/metrics/css/timeline/popularity/740
https://chromestatus.com/metrics/css/timeline/popularity/741
https://chromestatus.com/metrics/css/timeline/popularity/742

https://chromestatus.com/metrics/css/timeline/popularity/728
https://chromestatus.com/metrics/css/timeline/popularity/729
https://chromestatus.com/metrics/css/timeline/popularity/730
https://chromestatus.com/metrics/css/timeline/popularity/731

https://chromestatus.com/metrics/css/timeline/popularity/762

**Comment by BearCooder** [comment]
Some examples: 

- https://twitter.com/bramus/status/1701576910621311043

- https://twitter.com/bramusblog/status/1702826156313936251

- https://www.frontend.fyi/v/css-scroll-driven-animations

**Comment by thebabydino** [comment]
About a dozen more pure CSS examples:

- [scroll-triggered image reveal & zoom](https://codepen.io/thebabydino/pen/XWywJMW)  - reveal & zoom out of image once its parent figure has been scrolled into view to a certain extent (this was created as a pure CSS version of a JS-heavy [demo](https://codepen.io/cameronknight/pen/pogQKwR) I came across)
- [header slide effect on scroll](https://codepen.io/thebabydino/pen/YzJPRvd) - different palette depending on how far we've scrolled
![animated gif, showing how the `background` and the text `color` change from left to right as we scroll](https://github.com/web-platform-tests/interop/assets/76854602/2fb49390-5725-4e23-b790-1dc184bef702)
- [scroll-triggered animation](https://codepen.io/thebabydino/pen/qBQzPGY) - scrolling all the way to the end makes an animation start playing, while scrolling a bit back up again pauses it (basically toggles the `animation-play-state` value depending on whether we've scrolled all the way to the end on not)
- [invert text on scroll](https://codepen.io/thebabydino/pen/QWVLBqe) - how much of the page is inverted depended on how far we've scrolled
![screenshot showing the page scrolled a bit past half, which inverts a bit more than half from the left](https://github.com/web-platform-tests/interop/assets/76854602/c943eafc-e60c-476a-9230-ac190656137e)
- [flip through animal book on scroll](https://codepen.io/thebabydino/pen/RwqPeZY/dfd67fde1e4bb8c60040b5078c80ef92) - a remake of a 10+ year old [demo](https://codepen.io/thebabydino/pen/AYbjEa) I once made and which used many invisible hover triggers to flip through the book (as clever as I thought this was at the time, I now think it's an awful idea, please don't do this, there are [better ideas](https://twitter.com/anatudor/status/1704873894530757050) if you want to flip through the book depending on mouse position and not on scroll)
![animated gif showing how scrolling 3D flips through the pages of the animal book](https://github.com/web-platform-tests/interop/assets/76854602/6caab756-3016-4ebd-8020-9ac6d07955cf)
- [char by char reveal on scroll](https://codepen.io/thebabydino/pen/zYmVrRL/30397062d6f2c8442b0169f50a52460e) - a remake of something I saw on the Toblerone website, where it was done by wrapping every letter in a `div` (which I thought was quite awful) and using JS
![animated GIF showing the char by char text reveal on scroll](https://github.com/web-platform-tests/interop/assets/76854602/81e49602-e3a6-4eb1-8981-35f86edce7b9)
![screenshot with DevTools open so it's clear every letter is wrapped in an element](https://github.com/web-platform-tests/interop/assets/76854602/391e2d99-d611-4448-8fbd-4438082f8c36)
- [hue rotate on scroll](https://codepen.io/thebabydino/pen/BaqMVXy/88ab97f29398ac4167a15f8945f6dcb5) - selectively desaturating the page `background-image` and then rotating the hue of what's not desaturated + a few other subtle effects as we scroll (pure CSS, single image source version of this [demo](https://codepen.io/wakana-k/pen/OJBZQEo))
![animated GIF showing the hue rotate effect as we scroll](https://github.com/web-platform-tests/interop/assets/76854602/e3264d61-c586-4d6e-97eb-2dafb1ff2796)
- [3D globe axis tilt on scroll](https://codepen.io/thebabydino/pen/BaqwvZb/c02a6ae9897f53f052e2571b6560af32)
- [🐌 shrink](https://codepen.io/thebabydino/pen/QWJRQXK/77e6ed6e1b02a4aa100cd383cbfca6e1) - scrolling reveals the text, updates the percentage value and spiral shrinks the image (pure CSS version of this JS-heavy [demo](https://codepen.io/jfksdca/pen/KKZjveJ))
![animated gif showing how scrolling down makes the image covering the entire page shrinks in a spira/ snail fashion revealing the text underneath, which reads "Our solutions use p% less water", where p% grows from 0% to 97% as we scroll](https://github.com/web-platform-tests/interop/assets/76854602/0e51bbe9-be9f-4ea9-96be-5a731c633b2d)
- [diagonal scroll reveal](https://codepen.io/thebabydino/pen/rNqPGMM/4ce044598b6da8df3aebfa38e047c0b5) - no JS version of this [demo](https://codepen.io/suez/pen/gadLre)
![animated GIF showing the diagonal scroll reveal effect](https://github.com/web-platform-tests/interop/assets/76854602/41d3d6fb-f54c-40e3-b28c-b740139d9a37)

Also on the topic of diagonal scroll, I made [this meta demo](https://codepen.io/thebabydino/pen/zYJKRyq), whose example text explains what's happening there. This demo uses JS, though that's because of `shape-outside` being tied to floats and not because of the scroll.
![animated gif illustrating the diagonal scroll](https://github.com/web-platform-tests/interop/assets/76854602/34a933f8-ca92-4928-a7cd-6a4e90e1cac8)

**Comment by kizu** [comment]
I did [write today a post](https://blog.kizu.dev/priority-game/) about which proposals from Interop 2024 I'd want to see go forward the most, and this one was in the first place. And I totally forgot that I wanted to provide here a list of articles I (and others) wrote about scroll-driven animations, which show the number of things they make possible:

My articles:

1. [“Future CSS: Wishes Granted by Scroll-driven Animations”](https://kizu.dev/scroll-driven-animations/)
2. [“Fit-to-Width Text”](https://kizu.dev/fit-to-width-text/) 
3. [“Position-Driven Styles”](https://kizu.dev/position-driven-styles/)
4. [“Scroll-Driven State Transfer”](https://kizu.dev/scroll-driven-state-transfer/)
5. And a smaller blog post [“Scroll-Driven Animations in Stable Chrome”](https://blog.kizu.dev/scroll-driven-animations-in-stable-chrome/)

Articles by others I did save links to (there were more, so only what I have at hand right now):

- [“Scroll-persisted State”](https://johannesodland.github.io/state/scroll-snap/scroll-driven-animations/2023/06/18/scroll-persisted-state.html) by @johannesodland
- [“Detect if an element can scroll or not”](https://www.bram.us/2023/09/16/solved-by-css-scroll-driven-animations-detect-if-an-element-can-scroll-or-not/) by @bramus
- [“Style an element based on the active Scroll Direction and Scroll Speed”](https://www.bram.us/2023/10/23/css-scroll-detection/) also by @bramus
- [“Control Pixel Art Sprites With CSS Scroll-Driven Animations”](https://jamesbasoo.com/blog/scroll-driven-pixel-art-sprite/) by @jbasoo

**Comment by ydaniv** [comment]
@jgraham the Web Animations part of SDA also has a huge part here. Today all these effects are done via JS, so having a JS API as a drop-in replacement is also super important.
For example, to sync non-CSS APIs e.g. canvas and video.
So even if the declarative part probably has a higher demand, the imperative part is still much needed!

**Comment by foolip** [comment]
Thank you for proposing Scroll-driven Animations for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
