### ISSUE TITLE
Carryover evaluation: Color Spaces and Functions

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#457]
Let's evaluate whether to continue the Color Spaces and Functions focus area in Interop 2024.

Original proposals:
- https://github.com/web-platform-tests/interop/issues/20 by @una
- https://github.com/web-platform-tests/interop/issues/109 by @nt1m

Tests:
- [All tests](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-color%20or%20label%3Ainterop-2023-color)
- [Failing tests](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%28label%3Ainterop-2022-color%20or%20label%3Ainterop-2023-color%29%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by foolip** [comment]
Something to consider if we continue this focus area is whether we should fold https://github.com/web-platform-tests/interop/issues/426 into it.

**Comment by foolip** [comment]
A look through the [unlabeled tests](https://wpt.fyi/results/css/css-color?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2022-color%20%21label%3Ainterop-2023-color) might also turn up valuable tests in case of scope expansion.

**Comment by jgraham** [comment]
I'd strongly prefer to add things that are basically new features to new focus areas rather than adding additional scope to existing focus areas. There are two reasons for this:
* It works better as a metric. If the new feature represents, say, 5% of the total tests it is going to drop the existing score by (about) 5%. For something that's already close to 100% that doesn't convey well that one feature is entirely missing.
* It works better for the process / implementations. New features should be fully assessed alongside other proposals rather than being tacked on to existing focus areas.

I think extending focus areas only really makes sense where there are more tests for basically the same scope (e.g. adding new tests for flexbox or grid that still cover the same feature, just with additional coverage, as we did last year).

**Comment by svgeesus** [comment]
> I'd strongly prefer to add things that are basically new features to new focus areas

That seems very reasonable to me. And [current WPT results for RCS](https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&q=relative) would show a nice improvement from this starting position:

![image](https://github.com/web-platform-tests/interop/assets/2506926/4012bd77-30cd-45ce-be5b-eba0012ea481)

**Comment by vasilisvg** [comment]
I was pointed in this direction. I’m not sure if this is exactly the right place but …
I think focus from color functions should only be shifted when important bugs are fixed. There’s this bug in the implementation of (ok)lch that makes it impossible to really use it. And it may very well break websites that use (ok)lch once it’s fixed.

☞ https://bugs.webkit.org/show_bug.cgi?id=255939
☞ https://bugzilla.mozilla.org/show_bug.cgi?id=1847421
☞ https://bugs.chromium.org/p/chromium/issues/detail?id=1440069&q=lch&can=2
