### ISSUE TITLE
Remove scrollbar tests for container queries

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#460]
### Test List

https://wpt.fyi/results/css/css-contain/container-queries/auto-scrollbars.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container
https://wpt.fyi/results/css/css-contain/container-queries/transition-scrollbars.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container

### Rationale

The difference in behavior between Chrome & WebKit comes from the fact Chrome displays a scrollbar gutter but WebKit doesn't in the testcase. This causes a different container query to match in the transition test and the first assertion to fail in the auto test. This is a difference not related to container queries core functionality.

**Comment by nt1m** [comment]
@lilles @andruud Can you review for Chromium?

@dholbert Can you review for Gecko?

**Comment by lilles** [comment]
Is that because of overlay scrollbars, or is it a bug in WebKit?

If WebKit is spec compliant we should also make sure the tests allow all spec-compliant behavior.

**Comment by nt1m** [comment]
@lilles I just checked and it sounds like the scrollbars spec says a gutter should display in this case, see table in: https://drafts.csswg.org/css-overflow-3/#scrollbar-layout . WebKit doesn't reserve one in this specific case, which leads to these 2 tests failing. This isn't directly related to container queries though.

**Comment by lilles** [comment]
Are there other test variants we could add where the scrollbar gutters would be correctly created in WebKit so that we have better coverage for scrollbar interactions with container queries? Scrollbar behavior was one of the worries when the spec was discussed in the first place.

Also interesting to know why Gecko also fail these tests.

**Comment by nt1m** [comment]
We could swap overflow-y: auto with overflow-y: scroll if that works.

**Comment by emilio** [comment]
My understanding is that there are three different layouts that we can come up with without overlay scrollbars, and WebKit/Gecko disagree with Blink on the final one due to how we implement container queries / when we decide to stop the layout loop.

 1. Element overflows vertically, but there's no scrollbar.
 2. Element doesn't overflow but there's a scrollbar (blink's answer).
 3. Element doesn't overflow and there's no scrollbar. The container is really 100px wide, even though the container query doesn't reflect that (webkit and gecko's answer).

Only (1) is blatantly wrong IMO. The other two answers seem legit. Blink's answer is slightly more correct, you could argue, in the sense that the container query state in this case ends up matching the layout state.

But IIRC that isn't always the case in Blink (see https://github.com/w3c/csswg-drafts/issues/7875). So might be worth for the test to assert that (1) doesn't happen, while allowing for (2) or (3).

**Comment by nt1m** [comment]
@lilles @emilio Given this layout difference, would it be possible to exclude those tests? I'm not sure how to modify this test to adjust to all browsers behaviors aside from using `overflow-y: scroll` (which might reduce the value of the test)

**Comment by emilio** [comment]
@nt1m Just removing the `assert_less_than(scroller.clientWidth, 100, "Expects a vertical scrollbar");` should allow for (2) or (3) right?

**Comment by nt1m** [comment]
That should fix the first test, yes, thanks. The second test is still affected however.

**Comment by nt1m** [comment]
@emilio I created this PR: https://github.com/web-platform-tests/wpt/pull/42142

**Comment by nt1m** [comment]
Closing this, as the first test is resolved, and the second test is indeed buggy in WebKit.
