### ISSUE TITLE
Carryover evaluation: Web Components

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#466]
To evaluate continuation of the Web Components focus area in Interop 2024

Original proposals:
- https://github.com/web-platform-tests/interop/issues/203
- https://github.com/web-platform-tests/interop/issues/204
- https://github.com/web-platform-tests/interop/issues/230
- https://github.com/web-platform-tests/interop/issues/231

Labeled tests (2023):
- [All tests](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-webcomponents)
- [Failing tests](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-webcomponents%20status%3A%21ok%20status%3A%21pass) 

Also consider the possibility of adding new tests in 2024

**Comment by foolip** [comment]
In [preliminary results from State of HTML 2023](https://github.com/web-platform-tests/interop/issues/550), Web Components was a common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?"

There might be more details to be found in the freeform text responses, but I haven't looked at them.
