### ISSUE TITLE
Carryover evaluation: Transforms

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#469]
To evaluate continuation of the Transforms focus area in Interop 2024

Original proposal:

- Carried over from 2021 and 2022

Labeled tests (2023):

- [All tests](https://wpt.fyi/results/css/css-transforms?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-transforms)
- [Failing tests](https://wpt.fyi/results/css/css-transforms?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-transforms%20status%3A%21ok%20status%3A%21pass)

Also consider the possibility of adding new tests in 2024

**Comment by dbaron** [comment]
A few things to consider:
* there's been some [moderately recent spec changes](https://lists.w3.org/Archives/Public/www-style/2021Nov/0002.html) that are not particularly well covered by tests, although I think there are at least a few tests.  It's probably worth checking that they're within the labeled tests.  I think as of recently they have pretty good interop, though.
* there are likely to be a few more spec changes soon, related to `backface-visibility`, based on the discussion starting in https://github.com/w3c/csswg-drafts/issues/918#issuecomment-1696711327 .  The goal of these changes would be to specify backface visibility in a coherent way that can be interoperable; I believe current interop is poor.  That said, this work *probably* isn't far enough along to be part of the test set for interop 2024.

**Comment by thebabydino** [comment]
There are also some issues with 3D transforms + `backdrop-filter`. This [demo](https://codepen.io/thebabydino/pen/yLqJoog) works in Chromium browsers, but not in Firefox.

**Comment by thebabydino** [comment]
> * there are likely to be a few more spec changes soon, related to `backface-visibility`, based on the discussion starting in [[css-transforms-2] Preserve-3d + backface visibility semantics need to be clarified w3c/csswg-drafts#918 (comment)](https://github.com/w3c/csswg-drafts/issues/918#issuecomment-1696711327) .  The goal of these changes would be to specify backface visibility in a coherent way that can be interoperable; I believe current interop is poor.  That said, this work _probably_ isn't far enough along to be part of the test set for interop 2024.

I just hit this again - ([test case](https://codepen.io/thebabydino/pen/BavMEzK)). I'd really like to see browsers behaving consistently here.

What I would expect is what Chromium browsers do, hiding everything on the back of the element with `backface-visibility: hidden`, including the text nodes.

But the text still shows post-rotation on the back face in Firefox even though the background and border don't show - related Firefox bugs 🪲 [1201471](https://bugzilla.mozilla.org/show_bug.cgi?id=1201471), 🪲 [1393554](https://bugzilla.mozilla.org/show_bug.cgi?id=1393554), 🪲 [1655224](https://bugzilla.mozilla.org/show_bug.cgi?id=1655224).

Asking around, it also looks like sometimes (?!) Safari does weird things and displays everything post-rotation on the back face ([one](https://twitter.com/JonthanFielding/status/1712038893116088807), [two](https://twitter.com/ahmadalfy/status/1712047812613914825) reports of this). I asked the question because I was seeing some background weirdness (like in [this recording](https://twitter.com/WebReflection/status/1712061242653790421)) when testing via Epiphany and was curious what actual Safari does... and results seem to vary.
