### ISSUE TITLE
Carryover evaluation: Masking

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#476]
To evaluate continuation of the Masking focus area in Interop 2024

Original proposal:

- https://github.com/web-platform-tests/interop/issues/148

Labeled tests (2023):

- [All tests](https://wpt.fyi/results/css/css-masking?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssmasking)
- [Failing tests](https://wpt.fyi/results/css/css-masking?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssmasking%20status%3A%21ok%20status%3A%21pass)

Also consider the possibility of adding new tests in 2024

**Comment by jsnkuhn** [comment]
As the person that specifically asked about better support for `mask-image` I must say I'm concerned to still see Chromes 18% support. I know that there are still 3 months left in the year but to see pretty much no progress on this at all 9 months into the year is honestly disheartening.

![image](https://github.com/web-platform-tests/interop/assets/1286791/2ff70c6d-31b6-4de0-a682-3cae92a6e4e5)

**Comment by foolip** [comment]
@jsnkuhn the Chrome team is working on the Masking focus area and we expect to make good progress in the last 3 months of the year.

**Comment by thebabydino** [comment]
Chromium browsers have a non-standard `text` value for `mask-clip` - any chance this could become standard? It could be so useful.

One use case is for [glassmorphism effects on text](https://css-tricks.com/icon-glassmorphism-effect-in-css/#aa-moving-towards-a-chrome-solution). This effect could also be achieved in Firefox using `element()`, but it requires an extra element.

![Chrome (top) and Firefox (bottom) screenshot collage of the emoji glassmorphism effect for comparison. The emojis are obviously different, but the result is otherwise pretty similar.](https://github.com/web-platform-tests/interop/assets/76854602/9a8b088f-e5cb-401f-8ac4-026c30c415b7)

Another use case is for getting such alpha XOR `:hover`/ `:focus` animated gradient ghost buttons.

![Screenshot. Shows the pastel ghost buttons filling up from the bottom to the top on hover and this fill XOR-ing the button text and icon.](https://github.com/web-platform-tests/interop/assets/76854602/d2010011-72e1-4682-8ce5-6f9ae1467f26)

---

Another missing feature of masking would be the ability to subtract a `mask` layer from the result of compositing the layers below it - we can currently only perform the subtraction the other way around. Though I guess cross-browser support for [`luminance`](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-mode#browser_compatibility) masks could help there.
