### ISSUE TITLE
CSS color module level 4

### ISSUE THREAD

**Issue by mayank99** [web-platform-tests/interop#488]
### Description

[css-color-4](https://www.w3.org/TR/css-color-4) is quite well-supported, but it's not perfect. There are some gaps, for instance, not all [system colors](https://www.w3.org/TR/css-color-4/#css-system-colors) are consistently supported in all engines. Particularly, `AccentColor`/`AccentColorText` are notably absent from Blink (broken) and WebKit (spoofed). It would be nice to get full consistency before it's forgotten (since work is already underway towards css-color-5).

### Rationale

The big use case for `AccentColor` specifically (since that's one of the glaring omissions currently) is [user-adaptive interfaces](https://fullystacked.net/posts/accentcolor/). 

- Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1338061&q=accentcolor&can=2
- Webkit standards position: https://github.com/WebKit/standards-positions/issues/136

**Comment by jensimmons** [comment]
> It would be nice to get full consistency before it's forgotten

Could you explain what you believe the role of an Interop Project Investigation Project should play in creating this consistency? What sorts of expertise should people joining the project have? What would they do? What discussions are needed? What's the goal of the group effort? 

Remember, the Interop Project is not the appropriate venue for continuing work on CSS web standards — that happens in the CSS Working Group. If the Color 4 spec needs work / needs to be improved in order to contain more information about how to implement it, then the CSSWG should take up that work. 

Interop Project Investigations are for planning and organizing efforts around WPT testing infrastructure, writing more tests, figuring out a particularly complicated situation that's blocking progress, etc. 

What is the vision for this investigation?

**Comment by mayank99** [comment]
It's possible I'm misunderstanding the role of the Interop project, but I was hoping that the Interop team could discuss the inconsistencies with browser vendors and figure out if it's possible to have a way forward. As far as I can tell, the specification is pretty solid.

There are already plenty of tests too. Scrolling through [css-color-4](https://www.w3.org/TR/css-color-4) you'll see some of the inconsistencies in test results, although there could probably be tests for more scenarios? For example, the [`system-color-consistency`](https://wpt.fyi/results/css/css-color/system-color-consistency.html) test does not cover all system colors.

**Comment by lukewarlow** [comment]
Another example of an interop issue with system colours is `LinkText` and it's dark mode handling.

In Firefox LinkText changes in dark mode. Whereas in Chromium and Safari `LinkText` doesn't you have to use `-webkit-link`.

See `data:text/html,<a href="a">Foo</a><a href="b" class="dark">Foo</a><a href="c" class="dark-webkit">Foo</a><style>a {color-scheme: light;background-color:canvas;font-size:xx-large;padding:4px;color:linktext;} .dark{color-scheme:dark;} .dark-webkit{color-scheme:dark;color:-webkit-link}</style>` for an example.

**Comment by svgeesus** [comment]
@jensimmons thanks, agreed. I raised a couple of issues on CSSWG CSS Color 4 to capture the points raised here.

**Comment by jgraham** [comment]
Thank you for proposing CSS color module level 4 for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We believe this proposal is too broad, and that as such, Interop 2024 is not the right venue to do this investigation.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
