### ISSUE TITLE
hidden=until-found and auto-expanding details

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/interop#491]
### Description

These features allow users to reveal hidden but matching text in the page when using find-in-page, scroll to text fragment, or element fragment navigation. Auto-expanding details makes all `<details>` elements automatically expand when find-in-page or scroll to text finds match in their content and scrolls to it. The `hidden=until-found` attribute is a more generic version of this functionality which allows any element to be hidden until find-in-page or scroll to text fragment scrolls to it.

### Specification

https://html.spec.whatwg.org/multipage/interaction.html#attr-hidden-until-found-state

### Tests

hidden=until-found test for element fragment navigation: https://wpt.fyi/results/html/editing/the-hidden-attribute/beforematch-element-fragment-navigation.html

`<details>` test for element fragment navigation: https://wpt.fyi/results/html/semantics/interactive-elements/the-details-element/auto-expand-details-element-fragment.html?label=experimental&label=master&aligned

There are no WPTs for find-in-page because find-in-page is not testable in WPT.
There are no WPTs for scroll to text fragment because scroll to text fragment is not tested in WPT yet because I think it hasn't gotten specced yet? At least this was the case when I wrote the tests, but if this has changed then I could upstream them to WPT.

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

https://github.com/mozilla/standards-positions/issues/578
https://github.com/mozilla/standards-positions/issues/612
https://github.com/WebKit/standards-positions/issues/246
https://github.com/WebKit/standards-positions/issues/247

### Browser bug reports

https://bugzilla.mozilla.org/show_bug.cgi?id=1724299
https://bugs.webkit.org/show_bug.cgi?id=238266
https://bugs.webkit.org/show_bug.cgi?id=228843

### Existing Usage

https://chromestatus.com/metrics/feature/timeline/popularity/4114

### Privacy Impact

There was a privacy concern that the new beforematch event would allow websites to know what the user is typing into find-in-page, but there was an existing vulnerability for find-in-page where scroll events would also emit the same information.

Both of these find-in-page issues were addressed in chromium by adding a delay before find-in-page would automatically scroll to matching text.

**Comment by foolip** [comment]
Thank you for proposing `hidden=until-found` and auto-expanding `details` for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
