### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by o-t-w** [web-platform-tests/interop#498]
### Description

Streams are [asynchronously iterable](https://2ality.com/2019/11/nodejs-streams-async-iteration.html#reading-from-readable-streams-via-for-await-of) in Node, Deno, Bun and Firefox but not in Chrome or Safari. This means for-await-of loop work for streams in Node/Deno/Bun/Firefox but not Chrome or Safari. This can cause some confusion, as [seen here](https://x.com/wesbos/status/1688973743622606848?s=20). 

This could be broadened if there are other inconsistencies or lacking implementations to do with streams. 

### Specification

https://streams.spec.whatwg.org/

### Current Implementations

- [ ] Blink
- [X] Gecko
- [ ] WebKit

### Browser bug reports

[Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=929585&q=&can=5&sort=-modified) with 46 stars

**Comment by foolip** [comment]
@o-t-w if I understand the scope of the proposal correctly, it's to implement https://github.com/whatwg/streams/pull/980 across browsers. The main tests added for that in https://github.com/web-platform-tests/wpt/pull/15097 are now here:
https://wpt.fyi/results/streams/readable-streams?label=master&label=experimental&aligned&q=async-iterator

Is that the scope you intended?

**Comment by domenic** [comment]
Other recent streams PRs which haven't yet reached all (or in some cases any) browsers, but had strong community driving and involvement, are:

- https://github.com/whatwg/streams/commit/8d7a0bf26eb2cc23e884ddbaac7c1da4b91cf2bc
- https://github.com/whatwg/streams/commit/007d729f1476f7f1ea34731ba9bd2becb702117e

**Comment by foolip** [comment]
@domenic can you list the tests for those?

**Comment by saschanaz** [comment]
* `.from()`: https://wpt.fyi/results/streams/readable-streams/from.any.html
* `cancel`: https://wpt.fyi/results/streams/transform-streams/cancel.any.html

(with corresponding other items generated from any.js)

**Comment by dandclark** [comment]
Thank you for proposing Streams for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
