### ISSUE TITLE
`inverted-colors` Media Query

### ISSUE THREAD

**Issue by lukewarlow** [web-platform-tests/interop#506]
### Description

Following on from Interop 2023s Media Queries 4 focus area, it would be good for some of Media Queries 5 to be focussed on next. This request is specifically for the `inverted-colors` media query, this has shipped in WebKit for a long time but has yet to be launched in Firefox and Chromium.

### Specification

https://drafts.csswg.org/mediaqueries-5/#inverted

### Tests

https://wpt.fyi/results/css/mediaqueries/inverted-colors.html

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [X] WebKit

### Standards Positions

Mozilla Position: https://github.com/mozilla/standards-positions/issues/853

Mozilla Intent to Prototype: https://groups.google.com/a/mozilla.org/g/dev-platform/c/knC9tMRu_cw/m/lTUKB69TBwAJ

ChromeStatus: https://chromestatus.com/feature/5940010603773952

### Browser bug reports

Firefox Enable Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1846473

Chrome Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1462210

### Workarounds

There's no workaround for the lack of this feature.

### Accessibility Impact

This media query should increase accessibility by allowing sites to render better when inverted-colors is enabled.

### Privacy Impact

This feature does expose a new fingerprinting vector but it does already ship in WebKit.

### Other

Firefox has a complete implementation that just needs unflagging. Chromium requires the UA stylesheet addition which is blocked on some larger engineering effort to allow media feature queries in the UA stylesheets.

**Comment by cookiecrook** [comment]
WebKit already ships this and would likely not be opposed to including it in Interop 2024, but I want to fair by acknowledging many `prefers-*` media features have [outstanding privacy concerns](https://github.com/web-platform-tests/interop/issues/507#issuecomment-1743878685). Note: @lukewarlow made an interesting counter-proposal to [potentially address the privacy concern as an Interop research area](https://github.com/web-platform-tests/interop/issues/507#issuecomment-1743884396).

**Comment by lukewarlow** [comment]
See https://github.com/web-platform-tests/interop/issues/515

**Comment by dandclark** [comment]
Thank you for proposing `inverted-colors` Media Query for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
