### ISSUE TITLE
`video-dynamic-range` Media Query

### ISSUE THREAD

**Issue by lukewarlow** [web-platform-tests/interop#508]
### Description

Following on from Interop 2023s Media Queries 4 focus area, it would be good for some of Media Queries 5 to be focussed on next. This request is specifically for the [`video-dynamic-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/video-dynamic-range) media query, this has shipped in Firefox but not Chromium or WebKit.

### Specification

https://drafts.csswg.org/mediaqueries-5/#video-dynamic-range

### Tests

https://wpt.fyi/results/css/mediaqueries/dynamic-range.html

### Current Implementations

- [ ] Blink
- [X] Gecko
- [ ] WebKit

### Browser bug reports

WebKit Bug: https://bugs.webkit.org/show_bug.cgi?id=249678

Chrome Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1224711

### Privacy Impact

This exposes a new fingerprinting bit, but I don't think much more than what's already exposed by [`dynamic-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/dynamic-range)

**Comment by lukewarlow** [comment]
See https://github.com/web-platform-tests/interop/issues/515 (the issue is about preference media queries but could apply here too?)

**Comment by foolip** [comment]
@lukewarlow can you say something about the use cases for this, why it's important? Is it mainly to be able to use in `<video><source src=video-hdr.mov media="(video-dynamic-range: high)"></video>`?

**Comment by foolip** [comment]
cc @dalecurtis

**Comment by lukewarlow** [comment]
https://github.com/w3c/csswg-drafts/issues/4471 I think the summary at the top of this gives a pretty good explanation of the reason to have the two media queries and then yeah it'd mostly be used like you suggest choosing different media based on support.

**Comment by dandclark** [comment]
Thank you for proposing `video-dynamic-range` Media Query for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This proposal was not included in Interop 2024 because when we looked at its Web Platform Tests results, we found that it is already largely interoperable between tested browsers and does not need special coordinated attention.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
