### ISSUE TITLE
Media pseudo classes: `:paused`/`:playing`/`:seeking`/`:buffering`/`:stalled`/`:muted`/`:volume-locked`

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#510]
### Description

Pseudo classes to target specific states of video/audio elements including :has() support.

### Specification

https://w3c.github.io/csswg-drafts/selectors-4/#resource-pseudos

### Tests

https://wpt.fyi/css/selectors/media/media-loading-state.html
https://wpt.fyi/css/selectors/media/media-playback-state.html
https://wpt.fyi/css/selectors/media/sound-state.html
https://wpt.fyi/results/css/selectors/invalidation/media-pseudo-classes-in-has.html
https://wpt.fyi/results/css/selectors/invalidation/media-loading-pseudo-classes-in-has.html

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [X] WebKit

### Browser bug reports

https://bugzilla.mozilla.org/show_bug.cgi?id=1707584
https://bugs.chromium.org/p/chromium/issues/detail?id=1383480

### Workarounds

JavaScript

### Other

This is incredibly useful in combination with :has().

**Comment by foolip** [comment]
@nt1m I have a vague memory of a discussion to add these to https://html.spec.whatwg.org/#pseudo-classes but can't find any issue or PR in https://github.com/whatwg/html. Is there a plan to add these to the HTML spec? cc @annevk

**Comment by nt1m** [comment]
@foolip We can definitely add those to the HTML spec, but I don't think it's a blocker for this proposal given there's already a clear definition in the CSS spec.

**Comment by foolip** [comment]
@nt1m I agree the definitions in the CSS spec are clear enough in practice, but by adding normative definitions to HTML some of the text of the CSS spec could be removed.

I do not consider this a blocker.

**Comment by annevk** [comment]
I created https://github.com/whatwg/html/pull/10051 to add these to HTML.

**Comment by dandclark** [comment]
Thank you for proposing Media pseudo classes: `:paused`/`:playing`/`:seeking`/`:buffering`/`:stalled`/`:muted`/`:volume-locked` for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
