### ISSUE TITLE
CSS background-clip

### ISSUE THREAD

**Issue by jsnkuhn** [web-platform-tests/interop#517]
### Description

mdn:

> The background-clip CSS property sets whether an element's background extends underneath its border box, padding box, or content box.

Most existing inconsistencies seem to revolve around the `text` value.

The original webkit blog post for adding  -webkit-background-clip: text;: https://webkit.org/blog/164/background-clip-text/

### Specification

https://drafts.csswg.org/css-backgrounds-4/#background-clip

### Tests

https://wpt.fyi/results/css?label=master&label=experimental&aligned&q=background%20clip

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Browser bug reports

firefox bugs:
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=background-clip&list_id=16739518

[meta] background-clip:text issues
https://bugzilla.mozilla.org/show_bug.cgi?id=1656784

https://bugzilla.mozilla.org/show_bug.cgi?id=1481498

chrome:
Issue 1339290: Make -webkit-background-clip an alias
https://bugs.chromium.org/p/chromium/issues/detail?id=1339290&q=background-clip%20text&can=2

New chrome bug around how background-clip: text; works with position: https://bugs.chromium.org/p/chromium/issues/detail?id=1500148

**Comment by thebabydino** [comment]
I'd love to finally see this cross-browser!

I started using it as soon as it appeared in Firefox some 3.5 years ago, as it was easy to test support and polyfill it.

Even wrote [an article on the topic](https://css-tricks.com/a-lightweight-masonry-solution/) at the time, hoping it would encourage adoption and that my little fallback script would soon become obsolete.

Now it's 2023, still not supported by Chromium browsers and my little script has evolved a bit in the meanwhile (this is [the version](https://codepen.io/thebabydino/pen/xxmGLoJ/257bdc9acddf249cb3b467e40c9d6f1a) I'm currently using).

**Comment by thebabydino** [comment]
**Use case: a `:hover`/ `:focus` effect for links**

![Animated GIF. On hovering a link with an underline, the underline grows into a back highlight, which is then XOR-ed with the text.](https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/03/blend_0_ex_1a_step_13.gif?ssl=1)

The best way to do this is by having two background layers, one clipped to `text` and one to the `border-box`. The second layer is non-repeating vertically (only `repeat-x`), attached to the bottom (`background-position: 0 100%`) and initially occupies only a short box (something like `background-size: 1% 3px`).

On `:hover`/ `:focus`, the second layer grows upwards to fill the entire `border-box` (`background-size: 1% 100%`) and the two layers get XOR-ed using `background-blend-mode: difference` ([live demo](https://codepen.io/thebabydino/pen/bGBWeXM)).

The Firefox bug, which means the top layer's `background-image` is set across the union (and I'm using the word in the mathematical/ set theory sense) of the areas occupied by all layers, makes this technique fail (because the intersection of the two layers becomes the entire area occupied by the bottom layer).

A workaround would be to use an absolutely positioned pseudo and `mix-blend-mode` instead of the bottom layer, but this doesn't work properly for multi-line links ([live demo](https://codepen.io/thebabydino/pen/vYyxvZp)):

![Animated gif. Shows how in the case of a multi-line link, the pseudo-element is just between the left of the first word in the link text and the last word in the same link text.](https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/02/blend_0_ex_1a_step_08b.gif?ssl=1)

We could make the link `inline-block`, but this solution also comes with its own set of problems.

Similar effect: bubble navigation ([live demo](https://codepen.io/thebabydino/pen/vYyageY))

![Animated gif. Shows a random bubble growing from nothing and being blended with the text of a navigation link every time this is being hovered or focused.](https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/03/blend_0_ex_1c.gif?ssl=1)

Similar effect: selection-centric navbar([live demo](https://codepen.io/thebabydino/pen/mdVKQwj) - this is actually my own code replica of a navigation I saw on a supermarket website)

![image](https://github.com/web-platform-tests/interop/assets/76854602/7ec38765-6c6a-4ce8-ae28-33cd31c38a24)

**Use case: gradient ghost buttons**

![Screenshot. Gradient ghost buttons.](https://github.com/web-platform-tests/interop/assets/76854602/e963e3aa-6728-4a21-8512-8070ac11488c)

[Live demo](https://codepen.io/thebabydino/pen/ExvNBRY).

**Comment by jsnkuhn** [comment]
The original webkit blog post for adding ` -webkit-background-clip: text;`: https://webkit.org/blog/164/background-clip-text/

New chrome bug around how `background-clip: text;` works with `position`: https://bugs.chromium.org/p/chromium/issues/detail?id=1500148

**Comment by gsnedders** [comment]
We may well want to exclude Typed OM (#490) and the compute-kind-widget-generated tests, which leaveshttps://wpt.fyi/results/css?label=master&label=experimental&aligned&q=background-clip%20and%20not%20path%3A%2Fcss%2Fcss-ui%2Fcompute-kind-widget-generated%20and%20not%20path%3A%2Fcss%2Fcss-typed-om

This doesn't feel like we have many failing tests, but clearly there are other bugs mentioned in this thread.

**Comment by jsnkuhn** [comment]
New webkit bug for interaction between `background-blend-mode` and `background-clip: text;`: https://bugs.webkit.org/show_bug.cgi?id=267129

**Comment by yisibl** [comment]
> New webkit bug for interaction between `background-blend-mode` and `background-clip: text;`: https://bugs.webkit.org/show_bug.cgi?id=267129

@jsnkuhn For this issue, Firefox(123.0a1 (2024-01-04) ) also has bugs.

<img width="549" alt="image" src="https://github.com/web-platform-tests/interop/assets/2784308/3b95c3df-9d33-4042-a1ed-66e4e4c68a0b">

**Comment by thebabydino** [comment]
> @jsnkuhn For this issue, Firefox(123.0a1 (2024-01-04) ) also has bugs.

That's a completely different bug (nothing to do with blending, the problem is when a layer is clipped to text and another isn't), which I filed back in 2018 and already linked to above.

**Comment by dandclark** [comment]
Thank you for proposing CSS background-clip for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

The proposal was not on a standards track at the time of proposal selection, which made it unsuitable for inclusion in Interop 2024. Note that this should not be taken as a comment on the technology as a whole, or our willingness to take it up in the future.  If the feature is standardized, we would welcome this proposal being resubmitted for a future round of Interop.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
