### ISSUE TITLE
CSS Multi-Column Layout block element breaking

### ISSUE THREAD

**Issue by scottkellum** [web-platform-tests/interop#520]
### Description

CSS multi-column layout has a number of cross-browser issues making it difficult to use in an advanced way. Blink implements multi-column pretty well, but Webkit and Gecko 

With [this example](https://codepen.io/scottkellum/pen/qBQYyGO?editors=0100) you can see a number of these issues at play:

Blink — rendered correctly
<img width="1470" alt="A multi-column layout " src="https://github.com/web-platform-tests/interop/assets/377189/a1dc8338-aa0d-4869-a229-1e22b249cfe5">

Gecko — Truncated overflow, widow and orphan settings not respected
<img width="1470" alt="Screenshot 2023-10-03 at 12 47 00 PM" src="https://github.com/web-platform-tests/interop/assets/377189/8c2fcd4c-02b5-4b55-b418-8e0a7f18b083">

Webkit — Outlines incorrectly overflow to other columns, images sometimes flow into columns incorrectly.
<img width="1470" alt="Screenshot 2023-10-03 at 12 46 37 PM" src="https://github.com/web-platform-tests/interop/assets/377189/8c6e900c-b6d5-48ce-864e-851e548de791">

### Specification

https://www.w3.org/TR/css-multicol-1/

### Tests

https://wpt.fyi/results/css/css-multicol

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Existing Usage

https://codepen.io/scottkellum/pen/qBQYyGO

**Comment by clagnut** [comment]
I'm particularly keen to see the widow/orphan control respected, as in the example here where a heading is (but shouldn't be) the last item in a column. Essentially `break-after:avoid` not being respected. It looks bad in columns, put also reads really badly in paged media - people often forget that includes ePub ebooks, which is a far more common form of paged media than a printed web page. 

It's particularly embarrassing when an ebook one has written on typography fails these fundamental basics of typography ;-)

**Comment by clagnut** [comment]
I've added some more thoughts on the lack of support for `break-` properties in multicolumn layouts and paged media, along with a  test case here:

https://clagnut.com/blog/2426/
https://codepen.io/clagnut/pen/MWZRBaM

**Comment by nairnandu** [comment]
Thank you for proposing [CSS Multi-Column Layout block element breaking](https://github.com/web-platform-tests/interop/issues/520#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._

**Comment by clagnut** [comment]
Ok I guess I'll just have to keep prodding the bug report and keep my fingers crossed these bugs are finally fixed (after 26 years of waiting! Yes these bugs are older than some of my colleagues.)
