### ISSUE TITLE
URLPattern

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [web-platform-tests/interop#525]
### Description

The URLPattern API provides a web platform primitive for matching URLs based on conventional pattern syntax.

The specification already got positive feedback from Gecko https://github.com/mozilla/standards-positions/pull/893.

### Specification

https://github.com/whatwg/urlpattern

### Tests

https://wpt.fyi/results/urlpattern?label=experimental&label=master&aligned

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Gecko: https://github.com/mozilla/standards-positions/pull/893
WebKit: https://github.com/WebKit/standards-positions/issues/61

### Browser bug reports

https://bugs.chromium.org/p/chromium/issues/list?q=component:Blink%3EURLPattern

### Developer discussions

https://github.com/whatwg/urlpattern/issues

### Polls & Surveys

https://github.com/whatwg/urlpattern/blob/main/dev-trials-feedack.md

### Existing Usage

From other Web Platform API
- https://wicg.github.io/nav-speculation/speculation-rules.html
- https://github.com/WICG/service-worker-static-routing-api
- https://github.com/WICG/compression-dictionary-transport/issues/48

From JavaScript Runtime
- https://deno.land/api@v1.37.1?s=URLPattern

### Workarounds

https://www.npmjs.com/package/urlpattern-polyfill

### Accessibility Impact

URLPattern is for writing a URL pattern matching.  It should not affect accessibility directly.

### Privacy Impact

n/a.  URLPattern is a URL pattern matching mechanism.  APIs using the URLPattern API may have privacy impact, which is out of the URLPattern API’s scope.

### Other

n/a

**Comment by yoshisatoyanagisawa** [comment]
@sisidovski @jeremyroman FYI.

**Comment by sisidovski** [comment]
URLPattern is now in WHATWG. The repository was transferred from WICG into https://github.com/whatwg/urlpattern.

**Comment by yoshisatoyanagisawa** [comment]
Thanks for the heads up.  I have updated the URLs.

**Comment by lukewarlow** [comment]
https://urlpattern.spec.whatwg.org/ fyi it's now been published here

**Comment by nairnandu** [comment]
Thank you for proposing [URLPattern](https://github.com/web-platform-tests/interop/issues/525#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
