### ISSUE TITLE
Scrollend Events

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#528]
### Description

The scrollend event is fired when a scroll is completed. Not only is this helpful for web developers that wish to be notified when a scroll is completed, but this has the potential to improve the reliability of other wpt tests. (See the [various wait for scroll end functions that currently exist](https://searchfox.org/mozilla-central/search?q=function+waitForScrollEnd&path=testing%2Fweb-platform%2Ftest&case=false&regexp=false)).

### Specification

https://drafts.csswg.org/cssom-view/ (scrollend, scroll-completed, and scrolling-events)

### Tests

[dom/events/scrolling/scrollend-*](https://wpt.fyi/results/dom/events/scrolling?label=master&label=experimental&aligned&q=scrollend)

### Current Implementations

- [X] Blink
- [X] Gecko
- [ ] WebKit

### Standards Positions

https://github.com/WebKit/standards-positions/issues/150

### Browser bug reports

https://bugs.webkit.org/show_bug.cgi?id=201556 
https://bugzilla.mozilla.org/show_bug.cgi?id=1785102 

### Existing Usage

[Chrome use counter](https://chromestatus.com/metrics/feature/timeline/popularity/4419).

**Comment by jgraham** [comment]
CC @dlrobertson @hiikezoe @theres-waldo

**Comment by dlrobertson** [comment]
Note that the scrollend tests currently make use of touch scrolls for many of the tests. While testing scrollend for touch scrolls is helpful. It might make sense to move the vast majority of the webdriver action driven scrolls to use a normal scroll. See https://github.com/web-platform-tests/wpt/issues/42324.

**Comment by gsnedders** [comment]
Given Safari doesn't support touch events on macOS, the tests as currently written would still fail even if Safari supported `scrollend`.

**Comment by dlrobertson** [comment]
> Given Safari doesn't support touch events on macOS, the tests as currently written would still fail even if Safari supported `scrollend`.

@gsnedders yeah that makes sense. I'll create a PR to update the tests.

**Comment by foolip** [comment]
@dlrobertson did you get around to updating tests?

@gsnedders could this be tested with a scroll wheel fling? It is possible to scroll on macOS, as a user, after all :)

**Comment by dlrobertson** [comment]
If limiting the tests to cases that use programmatic scrolls, would be a reasonable subset to get some form of `scrollend` into interop, the following tests use only programmatic scrolls:

  - `dom/events/scrolling/scrollend-event-fired-for-programmatic-scroll.html`
  - `dom/events/scrolling/scrollend-event-fired-for-scrollIntoView.html`

**Comment by nairnandu** [comment]
Thank you for proposing [Scrollend Events](https://github.com/web-platform-tests/interop/issues/528#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
