### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by rejhgadellaa** [web-platform-tests/interop#534]
### Description

> The Notifications API allows web pages to control the display of system notifications to the end user. These are outside the top-level browsing context viewport, so therefore can be displayed even when the user has switched tabs or moved to a different app. The API is designed to be compatible with existing notification systems, across different platforms.
> [MDN - Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API)

While all major browser engines now support the Notification API (and related API's like Web Push, etcetera), there remain a lot of unsupported features.

Also, I know for a fact that Safari acts like it supports certain features, but they actually don't do anything. For example:

* `ServiceWorkerRegistration.showNotification()` would return a Promise that resolves to a list, but the list would always be empty. _Note: Safari 17 now behaves correctly, but previous versions did not_
* `Notification.close()` does not throw an error, but it doesn't do anything.

Beside these "no-ops", I would love to see support for actions, image, renotify, requireInteraction, silent, etcetera, in all major browsers.

### Specification

https://notifications.spec.whatwg.org/

### Tests

https://wpt.fyi/results/notifications

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Existing Usage

https://chromestatus.com/metrics/feature/timeline/popularity/371

**Comment by foolip** [comment]
Looking at https://wpt.fyi/results/notifications, it looks like the tests don't cover `requireInteraction` and some other things mentioned. https://github.com/web-platform-tests/wpt/tree/master/notifications has a bunch of manual tests, including for `requireInteraction`.

I think that in order to produce a score for this feature, either we'd to automate those tests (is that tractable?) or find a way to consider manual tests.

**Comment by nairnandu** [comment]
Thank you for proposing [Notifications API](https://github.com/web-platform-tests/interop/issues/534#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
