### ISSUE TITLE
WebTransport API

### ISSUE THREAD

**Issue by o-t-w** [web-platform-tests/interop#549]
### Description

An API particularly useful for gaming and livestreaming. 
Unlike older APIs, WebTransport enables unreliable datagrams, for data that is useless if it is late.
Similar to WebSockets but with a modern API that uses streams. 

### Specification

https://www.w3.org/TR/webtransport/

### Tests

https://wpt.fyi/results/webtransport?label=master&label=experimental&aligned&q=webtransport

### Current Implementations

- [X] Blink
- [X] Gecko
- [ ] WebKit

### Standards Positions

WebKit have expressed a [supportive position](https://github.com/WebKit/standards-positions/issues/18) on the standard.

### Polls & Surveys

It was not included in last years State of JS survey. 
In the [MDN APIs & JavaScript survey](https://github.com/web-platform-tests/interop/issues/246), WebTransport was selected by ~11% of survey takers.

### Existing Usage

Usage is [currently low,](https://chromestatus.com/metrics/feature/timeline/popularity/3472) which is not that surprising seeing as it is not implemented in Safari. 

Before it was shut down, it was used by [Google Stadia](https://groups.google.com/a/chromium.org/g/blink-dev/c/kwC5wES3I4c/m/2WxYhllhAAAJ):
“Google Stadia is using the WebTransport API in conjunction with the WebCodecs API for several use cases, both internally and with partners. The underlying WebTransport protocol, QUIC, has far greater throughput and resiliency characteristics than other mechanisms available, which enables use cases like webcams, and transmission of results of browser-based processing to applications and games in the cloud. The capability to transmit datagrams to cloud endpoints enables many new use cases for Stadia including communication with custom hardware endpoints. In the future we hope to explore using this API for other use cases.”

**Comment by foolip** [comment]
If this proposals makes it through the selection process there are some newer parts of the API like `sendOrder` that we'd prefer to exclude from scope.

**Comment by mehagar** [comment]
FWIW Webkit is implementing WebTransport now: https://github.com/WebKit/WebKit/pull/17320

**Comment by nairnandu** [comment]
Thank you for proposing [WebTransport API](https://github.com/web-platform-tests/interop/issues/549#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
