### ISSUE TITLE
P3 All The Things

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#559]
### Description

A lot of attention was paid in 2023 to implementing CSS features to let web designer/developers make use of wide gamut P3 color. But in order for CSS, media, and more to be in P3, the browser and operating system need to support P3 in all of the various levels of the DOM including:
- images
- video
- overall page
- Canvas (2D)
- Web GL (3D)
- SVG

Support for P3 color in Web GL was [proposed last year](https://github.com/web-platform-tests/interop/issues/168) by @astearns for Interop 2023:
> Rationale
> Wide color gamut support in WebGL Canvas is necessary for performant color management in apps like Photoshop on the web. We currently work around the lack by creating multiple Canvases which gets very memory-intensive.

### Specification

tbd

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

**Comment by svgeesus** [comment]
> images

Relevant WPT test for a Display P3 PNG image, using [cICP Coding Independent Code Points](https://www.w3.org/TR/png-3/#cICP-chunk) rather than an ICC profile:

[png](https://wpt.fyi/results/png?label=master&label=experimental&aligned)/[cicp-chunk.html](https://wpt.fyi/results/png/cicp-chunk.html?label=master&label=experimental&aligned)

Currently passes in Chrome and Edge, fails in Firefox and Safari

There should also be a test for an image with a Display P3 ICC profile, which I would expect all browsers to pass; that is easy to do but there is not currently such a test.

I agree that Display P3 Canvas 2D support would fit nicely into this area.

**Comment by jensimmons** [comment]
This definitely needs new tests. We need a volunteer. If we don't think we will have the tests, then this proposal should not be selected for Interop 2024.

**Comment by jensimmons** [comment]
This could instead be browsers self-reporting what's supported, and making sure that data is available on Can I Use.

**Comment by jgraham** [comment]
Thank you for proposing P3 All The Things for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We could not find any tests for P3 All The Things in the Web Platform Tests.  Such tests are crucial for measuring interoperability status and progress.  Once there are WPT entries covering this proposal, we welcome it being resubmitted for a future round of Interop.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
