### ISSUE TITLE
backdrop-filter

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#564]
### Description

`backdrop-filter` can be used to apply a filter effect to the underlying elements. The most common effect is probably a blur effect, as in this example from MDN:

![image](https://user-images.githubusercontent.com/498917/194866800-eb145e5e-fe2a-471c-9715-00d82da424f7.png)

### Specification

https://drafts.fxtf.org/filter-effects-2/#BackdropFilterProperty

### Open Issues

https://github.com/w3c/fxtf-drafts/issues?q=is%3Aissue+is%3Aopen+backdrop-filter

I have not checked the severity of any of the open issues.

### Tests

https://wpt.fyi/results/css/filter-effects?label=master&label=experimental&aligned&q=backdrop-filter

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Browser bug reports

https://bugs.webkit.org/show_bug.cgi?id=224899

### Polls & Surveys

`backdrop-filter` has showed up in State of CSS in the past, and again in 2023. It's never the _top_ issue, but keeps making an appearance.

Per https://2023.stateofcss.com/en-US/features/shapes-and-graphics/#backdrop_filter awareness is increasing.

Per https://2023.stateofcss.com/en-US/usage/#css_interoperability_features it's a bigger pain point than color functions and math functions. (Note https://github.com/Devographics/Monorepo/issues/324, this wasn't a freeform question even though the site currently says so.)

Quoting from https://github.com/web-platform-tests/interop/issues/210 about earlier surveys:

> In [State of CSS 2021](https://2021.stateofcss.com/en-US/opinions/#browser_interoperability_features), `backdrop-filter` was the 6th most common answer to the free-form question “Are there any CSS features you have difficulties using because of differences between browsers?”

> Adding to the rationale, `backdrop-filter` was a common responses the State of CSS 2022 question about browser incompatibilities, mentioned in ~3% of responses, see https://github.com/web-platform-tests/interop/issues/248.
>
> Representative examples are "Inconsistent backdrop-filter" and "backdrop-filter can be a pain!"

> In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS `backdrop-filter` property" was selected by ~21% of survey takers, putting it in the top third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

### Existing Usage

https://chromestatus.com/metrics/css/timeline/popularity/508

### Other

This is a resubmission of https://github.com/web-platform-tests/interop/issues/210 from Interop 2023 planning.

This is one of few properties that still require a prefix, namely `-webkit-backdrop-filter`.

**Comment by thebabydino** [comment]
This is often used for [glassmorphism](https://uxdesign.cc/glassmorphism-in-user-interfaces-1f39bb1308c9) effects.

These can get pretty tricky for text/ other non-rectangular shapes (detailed in [this article](https://github.com/w3c/csswg-drafts/issues/9456#issuecomment-1758992499) I wrote a couple of years back on getting such an effect for emoji icons).

But even simpler effects using rectangles that maybe have rounded corners can be problematic due to bugs.

**Example 1**. Consider this [glassmorphic credit card effect](https://www.cssscript.com/demo/glassmorphism-credit-card/).

[glass-card.webm](https://github.com/web-platform-tests/interop/assets/76854602/2537ddbe-b361-4d4b-9d4c-2034f99f0979)

The demo and tutorial in itself are Chrome-centric, but the reality is that this effect doesn't work in Firefox or Safari due to `backdrop-filter` bugs.

This effect requires a parent card with a front face child and a back face child. The back face child needs to be rotated by `.5turn` around its *y* axis and the parent needs to have `transform-style: preserve-3d`.

But `preserve-3d` on the parent breaks the `backdrop-filter` effect in Firefox - bug [1816561](https://bugzilla.mozilla.org/show_bug.cgi?id=1816561#c2).

And while I haven't had time to go into it, setting `backdrop-filter` on the faces of such an assembly makes the whole thing disappear altogether in Safari (tested via Epiphany).

Here's a [simplified test case](https://codepen.io/thebabydino/pen/vYvPxJB) for the card demo.

**Example 2**. I recently came across this [Dribbble animation](https://dribbble.com/shots/18943317-Animation).

[glass-ani.webm](https://github.com/web-platform-tests/interop/assets/76854602/9e910ce6-c0a6-4283-ada6-e4a4c51c84e0)

Took me only a few minutes to get [a working version](https://codepen.io/thebabydino/pen/VwqgrrE) in Chrome and then expanded it into [a second version](https://codepen.io/thebabydino/pen/OJrddJj) that works without animating custom properties registered via @property in order to extend support.

But both versions set `transform-style: preserve-3d` on the system parent so that when the two shapes orbiting the glass pass in front of it or behind, they are all in the correct order along the *z* axis. This means we hit the same bug as before in Firefox.

We can remove this property from the system parent, but this means *we lose the out of the box 3D* and we have to emulate it by switching `z-index` values at various points during the animation. Not ideal.

Safari does something even weirder here (tested via Epiphany) - it correctly blurs the shape passing behind the glass, but it also incorrectly creates a glow/ blur *around* the shape passing in *front* of the glass.

![Screenshot. Shows how not only does the shape passing behind the glass get blurred, but the one passing in front of it also gets a glow/ blur](https://github.com/web-platform-tests/interop/assets/76854602/463161d0-17f9-43b5-bec6-8496a370f2b6)

**Example 3**. Glassy cubes like in this [Dribbble animation](https://dribbble.com/shots/6026036-Glass-blocks) or even [intersecting ones](https://larameeee.tumblr.com/post/61852604066/bullseye-gallery-heike-brachlow-artistgeneral). This is one experiment I haven't found the time to get [too far](https://codepen.io/thebabydino/pen/yLqJoog) with.

![intersecting glassy cubes](https://github.com/web-platform-tests/interop/assets/76854602/21894018-e98a-4d84-9c51-e07f62a9cfe3)

**Comment by flackr** [comment]
Would we be able to resolve on the behavior proposed in https://github.com/w3c/fxtf-drafts/issues/374 as well? The current mirror edgemode leads to flickering when backdrop blur content is moving over new colors.

**Comment by jgraham** [comment]
Thank you for proposing backdrop-filter for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We did not have consensus to include this proposal. This should not be taken as a comment on the technology as a whole

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
