### ISSUE TITLE
Making the `display` and `content-visibility` CSS properties animatable

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/interop#583]
### Description

Making `display` animatable, in keyframes or transitions, makes animations to or from display:none possible. Dialogs and popovers both animate to or from display:none when entering or exiting the top layer, so this feature is needed in order to make top layer elements animatable: https://github.com/chrishtr/rendering/blob/master/entry-exit-animations.md

Making `content-visibility` animatable is useful in similar scenarios.

### Specification

https://drafts.csswg.org/css-display-4/#display-animation

### Tests

https://wpt.fyi/results/css/css-display/animations/display-interpolation.html
https://wpt.fyi/results/css/css-contain/content-visibility/content-visibility-interpolation.html

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Gecko: https://github.com/mozilla/standards-positions/issues/762

WebKit: https://github.com/WebKit/standards-positions/issues/147

### Browser bug reports

No bugs filed yet that I know of

### Existing Usage

I didn't create a use counter for this feature

**Comment by josepharhar** [comment]
Original proposal: https://github.com/web-platform-tests/interop/issues/495

**Comment by nairnandu** [comment]
Thank you for proposing [making the display and content-visibility CSS properties animatable](https://github.com/web-platform-tests/interop/issues/583#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
