### ISSUE TITLE
JSON Module Scripts

### ISSUE THREAD

**Issue by dandclark** [web-platform-tests/interop#596]
### Description

JSON modules (with import attributes) are a way to import JSON in JavaScript.

**Note: Per discussion of the interop team this proposal is split off from https://github.com/web-platform-tests/interop/issues/436 to be considered independently of CSS module scripts in proposal selection.
cc @o-t-w.**

### Specification

https://github.com/tc39/proposal-import-attributes
https://github.com/tc39/proposal-json-modules

### Open Issues

https://github.com/whatwg/html/issues/7233
There is an [open PR](https://github.com/whatwg/html/pull/9486) that would close this issue. 

### Tests

https://wpt.fyi/results/html/semantics/scripting-1/the-script-element?label=master&label=experimental&aligned&q=%28import-attributes%20or%20json%29%20and%20not%20assertions

### Current Implementations

- [X] Blink
- [ ] Gecko
- [X] WebKit

### Standards Positions

Safari Technology Preview supports import attributes and JSON modules. 

Chrome Canary is [currently updating](https://bugs.chromium.org/p/v8/issues/detail?id=13856#c11) the import attribute syntax from import assertions. 

### Browser bug reports

[Gecko bug for import attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=1736059). 

### Developer discussions

This Tweet has almost 900 likes https://x.com/mattpocockuk/status/1694679999117246640?s=20

### Accessibility Impact

No impact.

### Privacy Impact

No impact.

**Comment by jensimmons** [comment]
JSON module assertions is not standard, and should not be included in this proposal. 

Seems their tests will be marked optional. They should not be included in Interop 2024.
https://github.com/web-platform-tests/wpt/issues/42875

**Comment by dandclark** [comment]
Looks to me like the test link https://wpt.fyi/results/html/semantics/scripting-1/the-script-element?label=master&label=experimental&aligned&q=%28import-attributes%20or%20json%29%20and%20not%20assertions in the proposal is already excluding those and including only the versions with the new `with` keyword, but we should double-check after the changes proposed in https://github.com/web-platform-tests/wpt/issues/42875 land to make sure the right set of tests is still included.

**Comment by gsnedders** [comment]
FYI:

```
% rg 'assert[^_]' html/semantics/scripting-1/the-script-element/import-attributes html/semantics/scripting-1/the-script-element/json-module
html/semantics/scripting-1/the-script-element/import-attributes/dynamic-import-with-attributes-argument.any.js
16:        import("./export-hello.js", { assert: { type: "notARealType"} } ),
```

(There's other matches that aren't relevant.)

**Comment by nairnandu** [comment]
Thank you for proposing [JSON Module Scripts](https://github.com/web-platform-tests/interop/issues/596#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
