### ISSUE TITLE
CSS Module Scripts

### ISSUE THREAD

**Issue by dandclark** [web-platform-tests/interop#597]
### Description

CSS modules (with import attributes) are a way to import CSS files in JavaScript via the ES module syntax.

**Note: Per discussion of the interop team this proposal is split off from https://github.com/web-platform-tests/interop/issues/436 to be considered independently of JSON module scripts in proposal selection.
cc @o-t-w.**

### Specification

https://github.com/tc39/proposal-import-attributes
https://github.com/whatwg/html/pull/4898

### Open Issues

https://github.com/whatwg/html/issues/7233
There is an [open PR](https://github.com/whatwg/html/pull/9486) that would close this issue. 

### Tests

https://wpt.fyi/results/html/semantics/scripting-1/the-script-element?label=master&label=experimental&aligned&q=%28import-attributes%20or%20css%29%20and%20not%20assertions

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Safari Technology Preview supports import attributes. 
WebKit position on [CSS module scripts](https://github.com/WebKit/standards-positions/issues/77)

Chrome Canary is [currently updating](https://bugs.chromium.org/p/v8/issues/detail?id=13856#c11) the import attribute syntax from import assertions. 

Gecko standards position on [CSS modules](https://github.com/mozilla/standards-positions/issues/541)

### Browser bug reports

[Gecko bug for import attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=1736059). 
[Gecko bug for CSS modules scripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1720570) 

### Accessibility Impact

No impact.

### Privacy Impact

No impact.

**Comment by nairnandu** [comment]
Thank you for proposing [CSS Module Scripts](https://github.com/web-platform-tests/interop/issues/597#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
