### ISSUE TITLE
font-style for variable fonts with either Slant or Italic axes.

### ISSUE THREAD

**Issue by thlinard** [web-platform-tests/interop#64]
**Description**
Implementation of CSS Spec for font-style for variable fonts with either Slant or Italic axes.

**Specification**
[CSS Spec for font-style](https://www.w3.org/TR/css-fonts-4/#font-style-prop)

**Tests**
Links to web-platform-tests (on https://wpt.fyi) for the feature (this can be all tests, not a curated list): none, but https://arrowtype.github.io/vf-slnt-test/ (three test fonts are provided)

**Rationale**

The only style that works with a variable font with `slnt` or `ital` axis is the low-level control `font-variation-settings`.

The following styles and elements are only correctly supported (minus one detail, see https://arrowtype.github.io/vf-slnt-test/) by Firefox:
- `<i>`  element
- `font-style: italic; `
- `font-style: oblique;`
- `font-style: oblique XXdeg;`
- `font-style: oblique -XXdeg;`

Due to poor support, Google Fonts chose to stop releasing fonts with `ital` or `slnt` axis:

- [Support for Italic axis on API?](https://github.com/google/fonts/issues/2576)
- [[spec] How to handle slant axis in STAT table](https://github.com/googlefonts/gftools/issues/295)
- [Axis Registry: slant axis](https://github.com/google/fonts/issues/2606)
- [Inter fonts lacks italics.](https://github.com/google/fonts/issues/2386#issuecomment-1051407902)

Example of advice given by a site aimed at web developers:

> Due to some inconsistencies with how browsers handle variable font files that contain both italic and upright variants (and also files that contain both italic and slant axes), in these scenarios it’s best to omit the font-style line completely.
https://variablefonts.io/implementing-variable-fonts/

Relevant browser issues:

- [Chromium Issue 1064756: "font-style: italic doesn't activate the ital axis of variable fonts"](https://bugs.chromium.org/p/chromium/issues/detail?id=1064756)
- [WebKit Bugs #209565: "Variable fonts with 'slnt' or 'ital' axes are not rendered correctly with font-style:italic, etc"](https://bugs.webkit.org/show_bug.cgi?id=209565)

Relevant specification issues:

- [[css-fonts-4] Behavior for variable fonts with 'ital' axis ambiguous / underspec'ed](https://github.com/w3c/csswg-drafts/issues/3125) (regarding a lack of clarification in the CSS specs on what to do with `font-style: oblique XXdeg;` and a font that has only an `ital` axis)

Glossary:

- [Italic axis (ital)](https://fonts.google.com/knowledge/glossary/italic_axis)
- [Slant axis (slnt)](https://fonts.google.com/knowledge/glossary/slant_axis)

Specifications:

- [OpenType® Specification](https://learn.microsoft.com/en-us/typography/opentype/spec/)
- [CSS Fonts Module Level 3](https://drafts.csswg.org/css-fonts-3/#font-style-prop):
> **_italic_**
>     selects a font that is labeled as an italic face, or an oblique face if one is not 
> **_oblique_**
>     selects a font that is labeled as an oblique face, or an italic face if one is not

**Comment by thlinard** [comment]
Hi @foolip

Thanks, you can change the label, you sure know your processes better than me.

https://arrowtype.github.io/vf-slnt-test/ has recently been updated, with WOFF2 files for testing and CSS code (I'm not the author of this site). Is it enough for you?

Also, for the rationale, the same page compares the (very different) renderings of three browsers.

**Comment by gsnedders** [comment]
> Also, for the rationale, the same page compares the (very different) renderings of three browsers.

While this is true, why do web developers care about this feature? Do we have any evidence that they care about this feature? 

That's what the rationale section is trying to answer, not whether there's any incompatibility between browsers.

**Comment by thlinard** [comment]
> While this is true, why do web developers care about this feature? Do we have any evidence that they care about this feature?
> 
> That's what the rationale section is trying to answer, not whether there's any incompatibility between browsers.

Well, we've got a chicken and egg problem, then. Web developers aren't interested in a feature that doesn't work (or that only works on Firefox), and browser developers don't fix a feature that isn't used. Wasn't the present initiative precisely intended to go beyond that?

However, here are some relevant browser issues:

- [Chromium Issue 1064756: "font-style: italic doesn't activate the ital axis of variable fonts"](https://bugs.chromium.org/p/chromium/issues/detail?id=1064756)
- [WebKit Bugs #209565: "Variable fonts with 'slnt' or 'ital' axes are not rendered correctly with font-style:italic, etc"](https://bugs.webkit.org/show_bug.cgi?id=209565)

**Comment by jensimmons** [comment]
@thlinard I think you are misunderstanding what's going on. 

Interop 2023 is accepting new proposals from Sept 15 - October 15. After that, the team involved with the project will take all the proposals under consideration and choose which to include.

You've started such a proposal. But you need to make your case why this should be included. You need to show, with evidence, that this is something that fits the criteria. 

Sam and Philip aren't arguing against this technology. They are attempting to let you know what's missing from your proposal. They are trying to help you. Every proposal needs to include certain information. Just like any proposal — applying for a job, admission to college, or for a grant — you have to pitch your case. And your's simply isn't complete yet. And because of that, it's likely to not make it. 

So make your case! 

Don't assume everyone reading this already knows all font-style for variable fonts with either Slant or Italic axes. Read the README for details about what's expected. Explain: what is the current state? Is the web standard done? Who's implemented so far? What's missing for interoperability? How will including this in Interop 2023 help the web? 

There won't be time for everyone involved to go individually do this research. We need you to gather all the information and present it for us, so we _can_ take this under consideration.

**Comment by foolip** [comment]
@thlinard in addition to making the rationale as strong as you can, it would be great to ensure the spec is in order and the tests match it.

Does https://github.com/w3c/csswg-drafts/issues/3125 need to be resolved before the spec is clear on what should be implemented?

And can the tests in https://arrowtype.github.io/vf-slnt-test/ be turned into tests in web-platform-tests? In particular, is a special test font needed for this? The tests as now structured require a human to look for pink, and that's not easily done in WPT. The easiest is if it's possible to write [reftests](https://web-platform-tests.org/writing-tests/reftests.html), which compare two pages pixel-by-pixel, optionally with some fuzziness allowed.

**Comment by thlinard** [comment]
> Does [w3c/csswg-drafts#3125](https://github.com/w3c/csswg-drafts/issues/3125) need to be resolved before the spec is clear on what should be implemented?

In my opinion this is a minor point. The main thing that things as old as `<i>` and `font-style: italic;` work (by the way, maybe that's a source of the problem: nobody asks because everyone expects it works, and if not, they blame the font, not the browser). Resolve a lack of clarification in the CSS specs on what to do with `font-style: oblique XXdeg;` and a font that has only an `ital` axis would be a plus, for sure: in https://arrowtype.github.io/vf-slnt-test/, the expected result for Firefox is 🤷).
 
> And can the tests in https://arrowtype.github.io/vf-slnt-test/ be turned into tests in web-platform-tests? In particular, is a special test font needed for this? The tests as now structured require a human to look for pink, and that's not easily done in WPT. The easiest is if it's possible to write [reftests](https://web-platform-tests.org/writing-tests/reftests.html), which compare two pages pixel-by-pixel, optionally with some fuzziness allowed.

I just tried to draw attention to an issue, unfortunately I'm not the author of https://arrowtype.github.io/vf-slnt-test, @thundernixon is. @arrowtype or Stephen Nixon is much better qualified than me for such tests.

**Comment by drott** [comment]
FWIW I filed [crbug.com/1371880](https://bugs.chromium.org/p/chromium/issues/detail?id=1371880) for what looks like redundant synthesis in the `slnt` cases of the test page.

Regarding this proposal: 

- I am tentatively in favor of fixing the `slnt` cases and having this be part of this proposal.

@foolip wrote:
> And can the tests in https://arrowtype.github.io/vf-slnt-test/ be turned into tests in web-platform-tests?

- Yes, it looks like https://arrowtype.github.io/vf-slnt-test/ is based on the open source [Recursive](https://github.com/arrowtype/recursive) font. Modifying the font and subsetting and building it into some static reference fonts makes it possible to build reftests.  (There might be some clarification in the CSS spec needed of what a standard `italic` and `oblique` should map to in terms of `slnt` angle values applied to the font (can't tell off-hand)).

- For the `ital` axis, I would like to see a stronger rationale. IMO (open to be convinced otherwise) the `ital` axis is more of a backwards compatibility concept in variable fonts and it's mostly binary 0,1 representation is a bit add odds with variations, even if it's possible to map something like `oblique 20deg` to somewhere between that 0,1. For the latter case, `ital` usage is underspec'ed, hence https://github.com/w3c/csswg-drafts/issues/3125 is relevant.

Questions: 

- Can we agree on Interop targets without a set of tests? Where would the tests come from? @jfkthame, does Firefox use a set of tests to test `italic` & `oblique` with `slnt` fonts, which are non WPT tests?

**Comment by jfkthame** [comment]
> Where would the tests come from? @jfkthame, does Firefox use a set of tests to test `italic` & `oblique` with `slnt` fonts, which are non WPT tests?

No, I don't recall that we have tests covering that.

As suggested above, creating a set of static reference fonts is probably the way forward for more extensive `slnt` tests.

(And as for the `ital` axis, I think it was a mistaken idea and just shouldn't exist....)

**Comment by thlinard** [comment]
> (And as for the `ital` axis, I think it was a mistaken idea and just shouldn't exist....)

Support for the slant axis would already be great, if you want I can limit the issue (in its title and its description) to that.

**Comment by nairnandu** [comment]
Thank you for proposing font-style for Variable Fonts with either slant or italic axes for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop†int this year. For the `ital` axis there is an [unresolved spec issue](https://github.com/w3c/csswg-drafts/issues/3125) preventing interoperable implementations. For the `slnt` axis tests were added to WPT thanks to your report and this proposal. Nevertheless, we had many strong proposals, and could not accept them all.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
