### ISSUE TITLE
Remove html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#99]
** Test List **

html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.html

** Rationale **

It does pass on WebKit infrastructure: https://searchfox.org/wubkat/source/LayoutTests/imported/w3c/web-platform-tests/html/semantics/forms/the-input-element/range-restore-oninput-onchange-event-expected.txt

It does not pass on wpt.fyi however, quoting @cdumez, because:

> The reason for that is that the back/forward cache is enabled in Safari but disabled in WebKitTestRunner. The test times out in Safari because it is never getting a load event on back navigation, because the we restored the page from the back/forward cache. The test passes in Chrome and Firefox because they don't allow back/forward caching of pages with an opener.

cc @jensimmons

**Comment by foolip** [comment]
Can this test be written to be compatible with bfcache instead?

**Comment by jgraham** [comment]
Or we could use a cross-browser way to inhibit bfcache.

**Comment by cdumez** [comment]
`HTTPS + Cache-Control: no-store` would inhibit the bfcache for WebKit (and likely other browsers)

**Comment by foolip** [comment]
Here's the test:
https://github.com/web-platform-tests/wpt/blob/master/html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.html

A new window is `window.open()`'d and I guess the problem is that `w.history.back()` never ends up firing an event. But are there other ways of checking that the navigation happened, that makes the test work whether it's in bfcache or not? The "pageshow" event perhaps?

**Comment by foolip** [comment]
@mfreed7 @josepharhar do either of you have experience with this test, can you give input?

**Comment by jgraham** [comment]
I thought adding an unload handler would be enough to prevent bfcache, but I'm not sure I'm correct.

@smaug---- your input here would be very useful.

**Comment by cdumez** [comment]
> I thought adding an unload handler would be enough to prevent bfcache, but I'm not sure I'm correct.

Not true in WebKit.

**Comment by cdumez** [comment]
> Here's the test: https://github.com/web-platform-tests/wpt/blob/master/html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.html
> 
> A new window is `window.open()`'d and I guess the problem is that `w.history.back()` never ends up firing an event. But are there other ways of checking that the navigation happened, that makes the test work whether it's in bfcache or not? The "pageshow" event perhaps?

Listening of the "pageshow" event would indeed detect the navigation even if coming from the bfcache. However, I don't think this is the way to fix this test since it validates form restoration on history traversal and expected certain form control events. If the page came out of the bfcache then there would be no form restoration or form control events since the form controls would come out of the cache as-is with their last values already in there.

I think the way to fix this test is to somehow opt out of bfcache. The most reliable way I know is `HTTP + Cache-Control: no-store`.

**Comment by foolip** [comment]
Alright, can someone experiment with HTTPS + `Cache-Control: no-store`? Is it `resources/${type}-restore-events.html` that would have to be served with that header?

**Comment by cdumez** [comment]
> Alright, can someone experiment with HTTPS + `Cache-Control: no-store`? Is it `resources/${type}-restore-events.html` that would have to be served with that header?

I guess I can experiment since WebKit is the one bf caching.

**Comment by cdumez** [comment]
https://github.com/web-platform-tests/wpt/pull/35341

**Comment by cdumez** [comment]
I had to rename the test to make it https. Does anything need to be done to update the test name in Interop?

**Comment by nt1m** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/2932

**Comment by nt1m** [comment]
Sounds like there isn't anything else to do here, closing. Thanks Chris!

**Comment by foolip** [comment]
Thanks for helping sort this out, @cdumez and @nt1m!

**Comment by vinhill** [comment]
Since this change, the test is [failing](https://wpt.fyi/results/html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.https.html?label=experimental&label=master&aligned) on Firefox, see [bug 1783245](https://bugzilla.mozilla.org/show_bug.cgi?id=1783245) and [this](https://hg.mozilla.org/mozilla-central/rev/43cd8fe50bb0) commit.

Also, if this test is aimed at [restoring persistent state](https://html.spec.whatwg.org/#restore-persisted-state), we should assert that bfcache is not active (e.g. by changing the value of a span) and make this test optional.

@cdumez do you know of other ways to disable bfcache in Safari? I'm still investigating why `no-store` makes the test fail on Firefox. But to my knowledge, the HTML Spec defines no interaction between no-store and bfcache and browsers behave differently for `no-store`.

**Comment by hsinyi** [comment]
Reopen this for reviewing and addressing vinhill's [comment](https://github.com/web-platform-tests/interop/issues/99#issuecomment-1578917091). Thanks!

**Comment by foolip** [comment]
This is the test on wpt.fyi:
https://wpt.fyi/results/html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.https.html
